// Code generated by ent, DO NOT EDIT.

package book

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the book type in the database.
	Label = "book"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPlatformID holds the string denoting the platform_id field in the database.
	FieldPlatformID = "platform_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldCover holds the string denoting the cover field in the database.
	FieldCover = "cover"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldTranslator holds the string denoting the translator field in the database.
	FieldTranslator = "translator"
	// FieldPublisher holds the string denoting the publisher field in the database.
	FieldPublisher = "publisher"
	// FieldPubDate holds the string denoting the pub_date field in the database.
	FieldPubDate = "pub_date"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// FieldReadDate holds the string denoting the read_date field in the database.
	FieldReadDate = "read_date"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldComment holds the string denoting the comment field in the database.
	FieldComment = "comment"
	// FieldExternal holds the string denoting the external field in the database.
	FieldExternal = "external"
	// FieldScrapedAt holds the string denoting the scraped_at field in the database.
	FieldScrapedAt = "scraped_at"
	// Table holds the table name of the book in the database.
	Table = "books"
)

// Columns holds all SQL columns for book fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPlatformID,
	FieldTitle,
	FieldURL,
	FieldCover,
	FieldAuthor,
	FieldCountry,
	FieldTranslator,
	FieldPublisher,
	FieldPubDate,
	FieldPrice,
	FieldRating,
	FieldReadDate,
	FieldStatus,
	FieldTags,
	FieldComment,
	FieldExternal,
	FieldScrapedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the Book queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPlatformID orders the results by the platform_id field.
func ByPlatformID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByCover orders the results by the cover field.
func ByCover(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCover, opts...).ToFunc()
}

// ByAuthor orders the results by the author field.
func ByAuthor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthor, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByTranslator orders the results by the translator field.
func ByTranslator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTranslator, opts...).ToFunc()
}

// ByPublisher orders the results by the publisher field.
func ByPublisher(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublisher, opts...).ToFunc()
}

// ByPubDate orders the results by the pub_date field.
func ByPubDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPubDate, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByReadDate orders the results by the read_date field.
func ByReadDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReadDate, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTags orders the results by the tags field.
func ByTags(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTags, opts...).ToFunc()
}

// ByComment orders the results by the comment field.
func ByComment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComment, opts...).ToFunc()
}

// ByExternal orders the results by the external field.
func ByExternal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternal, opts...).ToFunc()
}

// ByScrapedAt orders the results by the scraped_at field.
func ByScrapedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScrapedAt, opts...).ToFunc()
}
