// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// Bookmark is the predicate function for bookmark builders.
type Bookmark func(*sql.Selector)

// CommunityMeta is the predicate function for communitymeta builders.
type CommunityMeta func(*sql.Selector)

// FlomoMemo is the predicate function for flomomemo builders.
type FlomoMemo func(*sql.Selector)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Movie is the predicate function for movie builders.
type Movie func(*sql.Selector)

// Note is the predicate function for note builders.
type Note func(*sql.Selector)

// Platform is the predicate function for platform builders.
type Platform func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
