// Code generated by ent, DO NOT EDIT.

package flomomemo

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the flomomemo type in the database.
	Label = "flomo_memo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPlatformID holds the string denoting the platform_id field in the database.
	FieldPlatformID = "platform_id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldFiles holds the string denoting the files field in the database.
	FieldFiles = "files"
	// FieldMemoCreatedAt holds the string denoting the memo_created_at field in the database.
	FieldMemoCreatedAt = "memo_created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldScrapedAt holds the string denoting the scraped_at field in the database.
	FieldScrapedAt = "scraped_at"
	// Table holds the table name of the flomomemo in the database.
	Table = "flomo_memos"
)

// Columns holds all SQL columns for flomomemo fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPlatformID,
	FieldContent,
	FieldTags,
	FieldFiles,
	FieldMemoCreatedAt,
	FieldUpdatedAt,
	FieldScrapedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the FlomoMemo queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPlatformID orders the results by the platform_id field.
func ByPlatformID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformID, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByTags orders the results by the tags field.
func ByTags(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTags, opts...).ToFunc()
}

// ByFiles orders the results by the files field.
func ByFiles(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFiles, opts...).ToFunc()
}

// ByMemoCreatedAt orders the results by the memo_created_at field.
func ByMemoCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemoCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByScrapedAt orders the results by the scraped_at field.
func ByScrapedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScrapedAt, opts...).ToFunc()
}
