// Code generated by ent, DO NOT EDIT.

package flomomemo

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lifeink-ai/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldUserID, v))
}

// PlatformID applies equality check predicate on the "platform_id" field. It's identical to PlatformIDEQ.
func PlatformID(v int) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldPlatformID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldContent, v))
}

// Tags applies equality check predicate on the "tags" field. It's identical to TagsEQ.
func Tags(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldTags, v))
}

// Files applies equality check predicate on the "files" field. It's identical to FilesEQ.
func Files(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldFiles, v))
}

// MemoCreatedAt applies equality check predicate on the "memo_created_at" field. It's identical to MemoCreatedAtEQ.
func MemoCreatedAt(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldMemoCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldUpdatedAt, v))
}

// ScrapedAt applies equality check predicate on the "scraped_at" field. It's identical to ScrapedAtEQ.
func ScrapedAt(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldScrapedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLTE(FieldUserID, v))
}

// PlatformIDEQ applies the EQ predicate on the "platform_id" field.
func PlatformIDEQ(v int) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldPlatformID, v))
}

// PlatformIDNEQ applies the NEQ predicate on the "platform_id" field.
func PlatformIDNEQ(v int) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNEQ(FieldPlatformID, v))
}

// PlatformIDIn applies the In predicate on the "platform_id" field.
func PlatformIDIn(vs ...int) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldIn(FieldPlatformID, vs...))
}

// PlatformIDNotIn applies the NotIn predicate on the "platform_id" field.
func PlatformIDNotIn(vs ...int) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNotIn(FieldPlatformID, vs...))
}

// PlatformIDGT applies the GT predicate on the "platform_id" field.
func PlatformIDGT(v int) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGT(FieldPlatformID, v))
}

// PlatformIDGTE applies the GTE predicate on the "platform_id" field.
func PlatformIDGTE(v int) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGTE(FieldPlatformID, v))
}

// PlatformIDLT applies the LT predicate on the "platform_id" field.
func PlatformIDLT(v int) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLT(FieldPlatformID, v))
}

// PlatformIDLTE applies the LTE predicate on the "platform_id" field.
func PlatformIDLTE(v int) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLTE(FieldPlatformID, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldContainsFold(FieldContent, v))
}

// TagsEQ applies the EQ predicate on the "tags" field.
func TagsEQ(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldTags, v))
}

// TagsNEQ applies the NEQ predicate on the "tags" field.
func TagsNEQ(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNEQ(FieldTags, v))
}

// TagsIn applies the In predicate on the "tags" field.
func TagsIn(vs ...string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldIn(FieldTags, vs...))
}

// TagsNotIn applies the NotIn predicate on the "tags" field.
func TagsNotIn(vs ...string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNotIn(FieldTags, vs...))
}

// TagsGT applies the GT predicate on the "tags" field.
func TagsGT(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGT(FieldTags, v))
}

// TagsGTE applies the GTE predicate on the "tags" field.
func TagsGTE(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGTE(FieldTags, v))
}

// TagsLT applies the LT predicate on the "tags" field.
func TagsLT(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLT(FieldTags, v))
}

// TagsLTE applies the LTE predicate on the "tags" field.
func TagsLTE(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLTE(FieldTags, v))
}

// TagsContains applies the Contains predicate on the "tags" field.
func TagsContains(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldContains(FieldTags, v))
}

// TagsHasPrefix applies the HasPrefix predicate on the "tags" field.
func TagsHasPrefix(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldHasPrefix(FieldTags, v))
}

// TagsHasSuffix applies the HasSuffix predicate on the "tags" field.
func TagsHasSuffix(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldHasSuffix(FieldTags, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNotNull(FieldTags))
}

// TagsEqualFold applies the EqualFold predicate on the "tags" field.
func TagsEqualFold(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEqualFold(FieldTags, v))
}

// TagsContainsFold applies the ContainsFold predicate on the "tags" field.
func TagsContainsFold(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldContainsFold(FieldTags, v))
}

// FilesEQ applies the EQ predicate on the "files" field.
func FilesEQ(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldFiles, v))
}

// FilesNEQ applies the NEQ predicate on the "files" field.
func FilesNEQ(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNEQ(FieldFiles, v))
}

// FilesIn applies the In predicate on the "files" field.
func FilesIn(vs ...string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldIn(FieldFiles, vs...))
}

// FilesNotIn applies the NotIn predicate on the "files" field.
func FilesNotIn(vs ...string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNotIn(FieldFiles, vs...))
}

// FilesGT applies the GT predicate on the "files" field.
func FilesGT(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGT(FieldFiles, v))
}

// FilesGTE applies the GTE predicate on the "files" field.
func FilesGTE(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGTE(FieldFiles, v))
}

// FilesLT applies the LT predicate on the "files" field.
func FilesLT(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLT(FieldFiles, v))
}

// FilesLTE applies the LTE predicate on the "files" field.
func FilesLTE(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLTE(FieldFiles, v))
}

// FilesContains applies the Contains predicate on the "files" field.
func FilesContains(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldContains(FieldFiles, v))
}

// FilesHasPrefix applies the HasPrefix predicate on the "files" field.
func FilesHasPrefix(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldHasPrefix(FieldFiles, v))
}

// FilesHasSuffix applies the HasSuffix predicate on the "files" field.
func FilesHasSuffix(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldHasSuffix(FieldFiles, v))
}

// FilesIsNil applies the IsNil predicate on the "files" field.
func FilesIsNil() predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldIsNull(FieldFiles))
}

// FilesNotNil applies the NotNil predicate on the "files" field.
func FilesNotNil() predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNotNull(FieldFiles))
}

// FilesEqualFold applies the EqualFold predicate on the "files" field.
func FilesEqualFold(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEqualFold(FieldFiles, v))
}

// FilesContainsFold applies the ContainsFold predicate on the "files" field.
func FilesContainsFold(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldContainsFold(FieldFiles, v))
}

// MemoCreatedAtEQ applies the EQ predicate on the "memo_created_at" field.
func MemoCreatedAtEQ(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldMemoCreatedAt, v))
}

// MemoCreatedAtNEQ applies the NEQ predicate on the "memo_created_at" field.
func MemoCreatedAtNEQ(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNEQ(FieldMemoCreatedAt, v))
}

// MemoCreatedAtIn applies the In predicate on the "memo_created_at" field.
func MemoCreatedAtIn(vs ...string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldIn(FieldMemoCreatedAt, vs...))
}

// MemoCreatedAtNotIn applies the NotIn predicate on the "memo_created_at" field.
func MemoCreatedAtNotIn(vs ...string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNotIn(FieldMemoCreatedAt, vs...))
}

// MemoCreatedAtGT applies the GT predicate on the "memo_created_at" field.
func MemoCreatedAtGT(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGT(FieldMemoCreatedAt, v))
}

// MemoCreatedAtGTE applies the GTE predicate on the "memo_created_at" field.
func MemoCreatedAtGTE(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGTE(FieldMemoCreatedAt, v))
}

// MemoCreatedAtLT applies the LT predicate on the "memo_created_at" field.
func MemoCreatedAtLT(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLT(FieldMemoCreatedAt, v))
}

// MemoCreatedAtLTE applies the LTE predicate on the "memo_created_at" field.
func MemoCreatedAtLTE(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLTE(FieldMemoCreatedAt, v))
}

// MemoCreatedAtContains applies the Contains predicate on the "memo_created_at" field.
func MemoCreatedAtContains(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldContains(FieldMemoCreatedAt, v))
}

// MemoCreatedAtHasPrefix applies the HasPrefix predicate on the "memo_created_at" field.
func MemoCreatedAtHasPrefix(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldHasPrefix(FieldMemoCreatedAt, v))
}

// MemoCreatedAtHasSuffix applies the HasSuffix predicate on the "memo_created_at" field.
func MemoCreatedAtHasSuffix(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldHasSuffix(FieldMemoCreatedAt, v))
}

// MemoCreatedAtEqualFold applies the EqualFold predicate on the "memo_created_at" field.
func MemoCreatedAtEqualFold(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEqualFold(FieldMemoCreatedAt, v))
}

// MemoCreatedAtContainsFold applies the ContainsFold predicate on the "memo_created_at" field.
func MemoCreatedAtContainsFold(v string) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldContainsFold(FieldMemoCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLTE(FieldUpdatedAt, v))
}

// ScrapedAtEQ applies the EQ predicate on the "scraped_at" field.
func ScrapedAtEQ(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldEQ(FieldScrapedAt, v))
}

// ScrapedAtNEQ applies the NEQ predicate on the "scraped_at" field.
func ScrapedAtNEQ(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNEQ(FieldScrapedAt, v))
}

// ScrapedAtIn applies the In predicate on the "scraped_at" field.
func ScrapedAtIn(vs ...time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldIn(FieldScrapedAt, vs...))
}

// ScrapedAtNotIn applies the NotIn predicate on the "scraped_at" field.
func ScrapedAtNotIn(vs ...time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldNotIn(FieldScrapedAt, vs...))
}

// ScrapedAtGT applies the GT predicate on the "scraped_at" field.
func ScrapedAtGT(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGT(FieldScrapedAt, v))
}

// ScrapedAtGTE applies the GTE predicate on the "scraped_at" field.
func ScrapedAtGTE(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldGTE(FieldScrapedAt, v))
}

// ScrapedAtLT applies the LT predicate on the "scraped_at" field.
func ScrapedAtLT(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLT(FieldScrapedAt, v))
}

// ScrapedAtLTE applies the LTE predicate on the "scraped_at" field.
func ScrapedAtLTE(v time.Time) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.FieldLTE(FieldScrapedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FlomoMemo) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FlomoMemo) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FlomoMemo) predicate.FlomoMemo {
	return predicate.FlomoMemo(sql.NotPredicates(p))
}
