// Code generated by ent, DO NOT EDIT.

package movie

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lifeink-ai/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldUserID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldTitle, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldURL, v))
}

// Cover applies equality check predicate on the "cover" field. It's identical to CoverEQ.
func Cover(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldCover, v))
}

// ReleaseDate applies equality check predicate on the "release_date" field. It's identical to ReleaseDateEQ.
func ReleaseDate(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldReleaseDate, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v int) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldRating, v))
}

// WatchDate applies equality check predicate on the "watch_date" field. It's identical to WatchDateEQ.
func WatchDate(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldWatchDate, v))
}

// Tags applies equality check predicate on the "tags" field. It's identical to TagsEQ.
func Tags(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldTags, v))
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldComment, v))
}

// ScrapedAt applies equality check predicate on the "scraped_at" field. It's identical to ScrapedAtEQ.
func ScrapedAt(v time.Time) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldScrapedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldUserID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldTitle, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldURL, v))
}

// CoverEQ applies the EQ predicate on the "cover" field.
func CoverEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldCover, v))
}

// CoverNEQ applies the NEQ predicate on the "cover" field.
func CoverNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldCover, v))
}

// CoverIn applies the In predicate on the "cover" field.
func CoverIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldCover, vs...))
}

// CoverNotIn applies the NotIn predicate on the "cover" field.
func CoverNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldCover, vs...))
}

// CoverGT applies the GT predicate on the "cover" field.
func CoverGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldCover, v))
}

// CoverGTE applies the GTE predicate on the "cover" field.
func CoverGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldCover, v))
}

// CoverLT applies the LT predicate on the "cover" field.
func CoverLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldCover, v))
}

// CoverLTE applies the LTE predicate on the "cover" field.
func CoverLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldCover, v))
}

// CoverContains applies the Contains predicate on the "cover" field.
func CoverContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldCover, v))
}

// CoverHasPrefix applies the HasPrefix predicate on the "cover" field.
func CoverHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldCover, v))
}

// CoverHasSuffix applies the HasSuffix predicate on the "cover" field.
func CoverHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldCover, v))
}

// CoverIsNil applies the IsNil predicate on the "cover" field.
func CoverIsNil() predicate.Movie {
	return predicate.Movie(sql.FieldIsNull(FieldCover))
}

// CoverNotNil applies the NotNil predicate on the "cover" field.
func CoverNotNil() predicate.Movie {
	return predicate.Movie(sql.FieldNotNull(FieldCover))
}

// CoverEqualFold applies the EqualFold predicate on the "cover" field.
func CoverEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldCover, v))
}

// CoverContainsFold applies the ContainsFold predicate on the "cover" field.
func CoverContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldCover, v))
}

// ReleaseDateEQ applies the EQ predicate on the "release_date" field.
func ReleaseDateEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldReleaseDate, v))
}

// ReleaseDateNEQ applies the NEQ predicate on the "release_date" field.
func ReleaseDateNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldReleaseDate, v))
}

// ReleaseDateIn applies the In predicate on the "release_date" field.
func ReleaseDateIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldReleaseDate, vs...))
}

// ReleaseDateNotIn applies the NotIn predicate on the "release_date" field.
func ReleaseDateNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldReleaseDate, vs...))
}

// ReleaseDateGT applies the GT predicate on the "release_date" field.
func ReleaseDateGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldReleaseDate, v))
}

// ReleaseDateGTE applies the GTE predicate on the "release_date" field.
func ReleaseDateGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldReleaseDate, v))
}

// ReleaseDateLT applies the LT predicate on the "release_date" field.
func ReleaseDateLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldReleaseDate, v))
}

// ReleaseDateLTE applies the LTE predicate on the "release_date" field.
func ReleaseDateLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldReleaseDate, v))
}

// ReleaseDateContains applies the Contains predicate on the "release_date" field.
func ReleaseDateContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldReleaseDate, v))
}

// ReleaseDateHasPrefix applies the HasPrefix predicate on the "release_date" field.
func ReleaseDateHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldReleaseDate, v))
}

// ReleaseDateHasSuffix applies the HasSuffix predicate on the "release_date" field.
func ReleaseDateHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldReleaseDate, v))
}

// ReleaseDateIsNil applies the IsNil predicate on the "release_date" field.
func ReleaseDateIsNil() predicate.Movie {
	return predicate.Movie(sql.FieldIsNull(FieldReleaseDate))
}

// ReleaseDateNotNil applies the NotNil predicate on the "release_date" field.
func ReleaseDateNotNil() predicate.Movie {
	return predicate.Movie(sql.FieldNotNull(FieldReleaseDate))
}

// ReleaseDateEqualFold applies the EqualFold predicate on the "release_date" field.
func ReleaseDateEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldReleaseDate, v))
}

// ReleaseDateContainsFold applies the ContainsFold predicate on the "release_date" field.
func ReleaseDateContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldReleaseDate, v))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v int) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v int) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...int) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...int) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v int) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v int) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v int) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v int) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldRating, v))
}

// RatingIsNil applies the IsNil predicate on the "rating" field.
func RatingIsNil() predicate.Movie {
	return predicate.Movie(sql.FieldIsNull(FieldRating))
}

// RatingNotNil applies the NotNil predicate on the "rating" field.
func RatingNotNil() predicate.Movie {
	return predicate.Movie(sql.FieldNotNull(FieldRating))
}

// WatchDateEQ applies the EQ predicate on the "watch_date" field.
func WatchDateEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldWatchDate, v))
}

// WatchDateNEQ applies the NEQ predicate on the "watch_date" field.
func WatchDateNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldWatchDate, v))
}

// WatchDateIn applies the In predicate on the "watch_date" field.
func WatchDateIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldWatchDate, vs...))
}

// WatchDateNotIn applies the NotIn predicate on the "watch_date" field.
func WatchDateNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldWatchDate, vs...))
}

// WatchDateGT applies the GT predicate on the "watch_date" field.
func WatchDateGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldWatchDate, v))
}

// WatchDateGTE applies the GTE predicate on the "watch_date" field.
func WatchDateGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldWatchDate, v))
}

// WatchDateLT applies the LT predicate on the "watch_date" field.
func WatchDateLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldWatchDate, v))
}

// WatchDateLTE applies the LTE predicate on the "watch_date" field.
func WatchDateLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldWatchDate, v))
}

// WatchDateContains applies the Contains predicate on the "watch_date" field.
func WatchDateContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldWatchDate, v))
}

// WatchDateHasPrefix applies the HasPrefix predicate on the "watch_date" field.
func WatchDateHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldWatchDate, v))
}

// WatchDateHasSuffix applies the HasSuffix predicate on the "watch_date" field.
func WatchDateHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldWatchDate, v))
}

// WatchDateIsNil applies the IsNil predicate on the "watch_date" field.
func WatchDateIsNil() predicate.Movie {
	return predicate.Movie(sql.FieldIsNull(FieldWatchDate))
}

// WatchDateNotNil applies the NotNil predicate on the "watch_date" field.
func WatchDateNotNil() predicate.Movie {
	return predicate.Movie(sql.FieldNotNull(FieldWatchDate))
}

// WatchDateEqualFold applies the EqualFold predicate on the "watch_date" field.
func WatchDateEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldWatchDate, v))
}

// WatchDateContainsFold applies the ContainsFold predicate on the "watch_date" field.
func WatchDateContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldWatchDate, v))
}

// TagsEQ applies the EQ predicate on the "tags" field.
func TagsEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldTags, v))
}

// TagsNEQ applies the NEQ predicate on the "tags" field.
func TagsNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldTags, v))
}

// TagsIn applies the In predicate on the "tags" field.
func TagsIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldTags, vs...))
}

// TagsNotIn applies the NotIn predicate on the "tags" field.
func TagsNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldTags, vs...))
}

// TagsGT applies the GT predicate on the "tags" field.
func TagsGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldTags, v))
}

// TagsGTE applies the GTE predicate on the "tags" field.
func TagsGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldTags, v))
}

// TagsLT applies the LT predicate on the "tags" field.
func TagsLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldTags, v))
}

// TagsLTE applies the LTE predicate on the "tags" field.
func TagsLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldTags, v))
}

// TagsContains applies the Contains predicate on the "tags" field.
func TagsContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldTags, v))
}

// TagsHasPrefix applies the HasPrefix predicate on the "tags" field.
func TagsHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldTags, v))
}

// TagsHasSuffix applies the HasSuffix predicate on the "tags" field.
func TagsHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldTags, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Movie {
	return predicate.Movie(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Movie {
	return predicate.Movie(sql.FieldNotNull(FieldTags))
}

// TagsEqualFold applies the EqualFold predicate on the "tags" field.
func TagsEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldTags, v))
}

// TagsContainsFold applies the ContainsFold predicate on the "tags" field.
func TagsContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldTags, v))
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldComment, v))
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldComment, v))
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldComment, vs...))
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldComment, vs...))
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldComment, v))
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldComment, v))
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldComment, v))
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldComment, v))
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContains(FieldComment, v))
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasPrefix(FieldComment, v))
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.Movie {
	return predicate.Movie(sql.FieldHasSuffix(FieldComment, v))
}

// CommentIsNil applies the IsNil predicate on the "comment" field.
func CommentIsNil() predicate.Movie {
	return predicate.Movie(sql.FieldIsNull(FieldComment))
}

// CommentNotNil applies the NotNil predicate on the "comment" field.
func CommentNotNil() predicate.Movie {
	return predicate.Movie(sql.FieldNotNull(FieldComment))
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldEqualFold(FieldComment, v))
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.Movie {
	return predicate.Movie(sql.FieldContainsFold(FieldComment, v))
}

// ScrapedAtEQ applies the EQ predicate on the "scraped_at" field.
func ScrapedAtEQ(v time.Time) predicate.Movie {
	return predicate.Movie(sql.FieldEQ(FieldScrapedAt, v))
}

// ScrapedAtNEQ applies the NEQ predicate on the "scraped_at" field.
func ScrapedAtNEQ(v time.Time) predicate.Movie {
	return predicate.Movie(sql.FieldNEQ(FieldScrapedAt, v))
}

// ScrapedAtIn applies the In predicate on the "scraped_at" field.
func ScrapedAtIn(vs ...time.Time) predicate.Movie {
	return predicate.Movie(sql.FieldIn(FieldScrapedAt, vs...))
}

// ScrapedAtNotIn applies the NotIn predicate on the "scraped_at" field.
func ScrapedAtNotIn(vs ...time.Time) predicate.Movie {
	return predicate.Movie(sql.FieldNotIn(FieldScrapedAt, vs...))
}

// ScrapedAtGT applies the GT predicate on the "scraped_at" field.
func ScrapedAtGT(v time.Time) predicate.Movie {
	return predicate.Movie(sql.FieldGT(FieldScrapedAt, v))
}

// ScrapedAtGTE applies the GTE predicate on the "scraped_at" field.
func ScrapedAtGTE(v time.Time) predicate.Movie {
	return predicate.Movie(sql.FieldGTE(FieldScrapedAt, v))
}

// ScrapedAtLT applies the LT predicate on the "scraped_at" field.
func ScrapedAtLT(v time.Time) predicate.Movie {
	return predicate.Movie(sql.FieldLT(FieldScrapedAt, v))
}

// ScrapedAtLTE applies the LTE predicate on the "scraped_at" field.
func ScrapedAtLTE(v time.Time) predicate.Movie {
	return predicate.Movie(sql.FieldLTE(FieldScrapedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Movie) predicate.Movie {
	return predicate.Movie(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Movie) predicate.Movie {
	return predicate.Movie(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Movie) predicate.Movie {
	return predicate.Movie(sql.NotPredicates(p))
}
