// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lifeink-ai/backend/ent/bookmark"
)

// Bookmark is the model entity for the Bookmark schema.
type Bookmark struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PlatformID holds the value of the "platform_id" field.
	PlatformID int `json:"platform_id,omitempty"`
	// BookID holds the value of the "book_id" field.
	BookID string `json:"book_id,omitempty"`
	// BookTitle holds the value of the "book_title" field.
	BookTitle *string `json:"book_title,omitempty"`
	// MarkText holds the value of the "mark_text" field.
	MarkText string `json:"mark_text,omitempty"`
	// ChapterName holds the value of the "chapter_name" field.
	ChapterName *string `json:"chapter_name,omitempty"`
	// ChapterIdx holds the value of the "chapter_idx" field.
	ChapterIdx *int `json:"chapter_idx,omitempty"`
	// Style holds the value of the "style" field.
	Style *int `json:"style,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime *int64 `json:"create_time,omitempty"`
	// BookmarkID holds the value of the "bookmark_id" field.
	BookmarkID *string `json:"bookmark_id,omitempty"`
	// ScrapedAt holds the value of the "scraped_at" field.
	ScrapedAt    time.Time `json:"scraped_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Bookmark) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bookmark.FieldID, bookmark.FieldUserID, bookmark.FieldPlatformID, bookmark.FieldChapterIdx, bookmark.FieldStyle, bookmark.FieldCreateTime:
			values[i] = new(sql.NullInt64)
		case bookmark.FieldBookID, bookmark.FieldBookTitle, bookmark.FieldMarkText, bookmark.FieldChapterName, bookmark.FieldBookmarkID:
			values[i] = new(sql.NullString)
		case bookmark.FieldScrapedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Bookmark fields.
func (_m *Bookmark) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bookmark.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case bookmark.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case bookmark.FieldPlatformID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field platform_id", values[i])
			} else if value.Valid {
				_m.PlatformID = int(value.Int64)
			}
		case bookmark.FieldBookID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field book_id", values[i])
			} else if value.Valid {
				_m.BookID = value.String
			}
		case bookmark.FieldBookTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field book_title", values[i])
			} else if value.Valid {
				_m.BookTitle = new(string)
				*_m.BookTitle = value.String
			}
		case bookmark.FieldMarkText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mark_text", values[i])
			} else if value.Valid {
				_m.MarkText = value.String
			}
		case bookmark.FieldChapterName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chapter_name", values[i])
			} else if value.Valid {
				_m.ChapterName = new(string)
				*_m.ChapterName = value.String
			}
		case bookmark.FieldChapterIdx:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chapter_idx", values[i])
			} else if value.Valid {
				_m.ChapterIdx = new(int)
				*_m.ChapterIdx = int(value.Int64)
			}
		case bookmark.FieldStyle:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field style", values[i])
			} else if value.Valid {
				_m.Style = new(int)
				*_m.Style = int(value.Int64)
			}
		case bookmark.FieldCreateTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(int64)
				*_m.CreateTime = value.Int64
			}
		case bookmark.FieldBookmarkID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bookmark_id", values[i])
			} else if value.Valid {
				_m.BookmarkID = new(string)
				*_m.BookmarkID = value.String
			}
		case bookmark.FieldScrapedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scraped_at", values[i])
			} else if value.Valid {
				_m.ScrapedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Bookmark.
// This includes values selected through modifiers, order, etc.
func (_m *Bookmark) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Bookmark.
// Note that you need to call Bookmark.Unwrap() before calling this method if this Bookmark
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Bookmark) Update() *BookmarkUpdateOne {
	return NewBookmarkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Bookmark entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Bookmark) Unwrap() *Bookmark {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Bookmark is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Bookmark) String() string {
	var builder strings.Builder
	builder.WriteString("Bookmark(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("platform_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlatformID))
	builder.WriteString(", ")
	builder.WriteString("book_id=")
	builder.WriteString(_m.BookID)
	builder.WriteString(", ")
	if v := _m.BookTitle; v != nil {
		builder.WriteString("book_title=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("mark_text=")
	builder.WriteString(_m.MarkText)
	builder.WriteString(", ")
	if v := _m.ChapterName; v != nil {
		builder.WriteString("chapter_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ChapterIdx; v != nil {
		builder.WriteString("chapter_idx=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Style; v != nil {
		builder.WriteString("style=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BookmarkID; v != nil {
		builder.WriteString("bookmark_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("scraped_at=")
	builder.WriteString(_m.ScrapedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Bookmarks is a parsable slice of Bookmark.
type Bookmarks []*Bookmark
