// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lifeink-ai/backend/ent/book"
)

// BookCreate is the builder for creating a Book entity.
type BookCreate struct {
	config
	mutation *BookMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *BookCreate) SetUserID(v int64) *BookCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPlatformID sets the "platform_id" field.
func (_c *BookCreate) SetPlatformID(v int) *BookCreate {
	_c.mutation.SetPlatformID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *BookCreate) SetTitle(v string) *BookCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *BookCreate) SetURL(v string) *BookCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetCover sets the "cover" field.
func (_c *BookCreate) SetCover(v string) *BookCreate {
	_c.mutation.SetCover(v)
	return _c
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_c *BookCreate) SetNillableCover(v *string) *BookCreate {
	if v != nil {
		_c.SetCover(*v)
	}
	return _c
}

// SetAuthor sets the "author" field.
func (_c *BookCreate) SetAuthor(v string) *BookCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_c *BookCreate) SetNillableAuthor(v *string) *BookCreate {
	if v != nil {
		_c.SetAuthor(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *BookCreate) SetCountry(v string) *BookCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *BookCreate) SetNillableCountry(v *string) *BookCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetTranslator sets the "translator" field.
func (_c *BookCreate) SetTranslator(v string) *BookCreate {
	_c.mutation.SetTranslator(v)
	return _c
}

// SetNillableTranslator sets the "translator" field if the given value is not nil.
func (_c *BookCreate) SetNillableTranslator(v *string) *BookCreate {
	if v != nil {
		_c.SetTranslator(*v)
	}
	return _c
}

// SetPublisher sets the "publisher" field.
func (_c *BookCreate) SetPublisher(v string) *BookCreate {
	_c.mutation.SetPublisher(v)
	return _c
}

// SetNillablePublisher sets the "publisher" field if the given value is not nil.
func (_c *BookCreate) SetNillablePublisher(v *string) *BookCreate {
	if v != nil {
		_c.SetPublisher(*v)
	}
	return _c
}

// SetPubDate sets the "pub_date" field.
func (_c *BookCreate) SetPubDate(v string) *BookCreate {
	_c.mutation.SetPubDate(v)
	return _c
}

// SetNillablePubDate sets the "pub_date" field if the given value is not nil.
func (_c *BookCreate) SetNillablePubDate(v *string) *BookCreate {
	if v != nil {
		_c.SetPubDate(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *BookCreate) SetPrice(v string) *BookCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *BookCreate) SetNillablePrice(v *string) *BookCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetRating sets the "rating" field.
func (_c *BookCreate) SetRating(v int) *BookCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_c *BookCreate) SetNillableRating(v *int) *BookCreate {
	if v != nil {
		_c.SetRating(*v)
	}
	return _c
}

// SetReadDate sets the "read_date" field.
func (_c *BookCreate) SetReadDate(v string) *BookCreate {
	_c.mutation.SetReadDate(v)
	return _c
}

// SetNillableReadDate sets the "read_date" field if the given value is not nil.
func (_c *BookCreate) SetNillableReadDate(v *string) *BookCreate {
	if v != nil {
		_c.SetReadDate(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BookCreate) SetStatus(v string) *BookCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BookCreate) SetNillableStatus(v *string) *BookCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *BookCreate) SetTags(v string) *BookCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_c *BookCreate) SetNillableTags(v *string) *BookCreate {
	if v != nil {
		_c.SetTags(*v)
	}
	return _c
}

// SetComment sets the "comment" field.
func (_c *BookCreate) SetComment(v string) *BookCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *BookCreate) SetNillableComment(v *string) *BookCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetExternal sets the "external" field.
func (_c *BookCreate) SetExternal(v string) *BookCreate {
	_c.mutation.SetExternal(v)
	return _c
}

// SetNillableExternal sets the "external" field if the given value is not nil.
func (_c *BookCreate) SetNillableExternal(v *string) *BookCreate {
	if v != nil {
		_c.SetExternal(*v)
	}
	return _c
}

// SetScrapedAt sets the "scraped_at" field.
func (_c *BookCreate) SetScrapedAt(v time.Time) *BookCreate {
	_c.mutation.SetScrapedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BookCreate) SetID(v int64) *BookCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BookMutation object of the builder.
func (_c *BookCreate) Mutation() *BookMutation {
	return _c.mutation
}

// Save creates the Book in the database.
func (_c *BookCreate) Save(ctx context.Context) (*Book, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BookCreate) SaveX(ctx context.Context) *Book {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BookCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Book.user_id"`)}
	}
	if _, ok := _c.mutation.PlatformID(); !ok {
		return &ValidationError{Name: "platform_id", err: errors.New(`ent: missing required field "Book.platform_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Book.title"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Book.url"`)}
	}
	if _, ok := _c.mutation.ScrapedAt(); !ok {
		return &ValidationError{Name: "scraped_at", err: errors.New(`ent: missing required field "Book.scraped_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := book.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Book.id": %w`, err)}
		}
	}
	return nil
}

func (_c *BookCreate) sqlSave(ctx context.Context) (*Book, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BookCreate) createSpec() (*Book, *sqlgraph.CreateSpec) {
	var (
		_node = &Book{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(book.Table, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(book.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PlatformID(); ok {
		_spec.SetField(book.FieldPlatformID, field.TypeInt, value)
		_node.PlatformID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(book.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Cover(); ok {
		_spec.SetField(book.FieldCover, field.TypeString, value)
		_node.Cover = &value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
		_node.Author = &value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(book.FieldCountry, field.TypeString, value)
		_node.Country = &value
	}
	if value, ok := _c.mutation.Translator(); ok {
		_spec.SetField(book.FieldTranslator, field.TypeString, value)
		_node.Translator = &value
	}
	if value, ok := _c.mutation.Publisher(); ok {
		_spec.SetField(book.FieldPublisher, field.TypeString, value)
		_node.Publisher = &value
	}
	if value, ok := _c.mutation.PubDate(); ok {
		_spec.SetField(book.FieldPubDate, field.TypeString, value)
		_node.PubDate = &value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(book.FieldPrice, field.TypeString, value)
		_node.Price = &value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(book.FieldRating, field.TypeInt, value)
		_node.Rating = &value
	}
	if value, ok := _c.mutation.ReadDate(); ok {
		_spec.SetField(book.FieldReadDate, field.TypeString, value)
		_node.ReadDate = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(book.FieldStatus, field.TypeString, value)
		_node.Status = &value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(book.FieldTags, field.TypeString, value)
		_node.Tags = &value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(book.FieldComment, field.TypeString, value)
		_node.Comment = &value
	}
	if value, ok := _c.mutation.External(); ok {
		_spec.SetField(book.FieldExternal, field.TypeString, value)
		_node.External = &value
	}
	if value, ok := _c.mutation.ScrapedAt(); ok {
		_spec.SetField(book.FieldScrapedAt, field.TypeTime, value)
		_node.ScrapedAt = value
	}
	return _node, _spec
}

// BookCreateBulk is the builder for creating many Book entities in bulk.
type BookCreateBulk struct {
	config
	err      error
	builders []*BookCreate
}

// Save creates the Book entities in the database.
func (_c *BookCreateBulk) Save(ctx context.Context) ([]*Book, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Book, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BookCreateBulk) SaveX(ctx context.Context) []*Book {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
