// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lifeink-ai/backend/ent/book"
	"github.com/lifeink-ai/backend/ent/predicate"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BookUpdate) SetUserID(v int64) *BookUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BookUpdate) SetNillableUserID(v *int64) *BookUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *BookUpdate) AddUserID(v int64) *BookUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *BookUpdate) SetPlatformID(v int) *BookUpdate {
	_u.mutation.ResetPlatformID()
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePlatformID(v *int) *BookUpdate {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// AddPlatformID adds value to the "platform_id" field.
func (_u *BookUpdate) AddPlatformID(v int) *BookUpdate {
	_u.mutation.AddPlatformID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdate) SetTitle(v string) *BookUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTitle(v *string) *BookUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *BookUpdate) SetURL(v string) *BookUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *BookUpdate) SetNillableURL(v *string) *BookUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetCover sets the "cover" field.
func (_u *BookUpdate) SetCover(v string) *BookUpdate {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCover(v *string) *BookUpdate {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *BookUpdate) ClearCover() *BookUpdate {
	_u.mutation.ClearCover()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *BookUpdate) SetAuthor(v string) *BookUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *BookUpdate) SetNillableAuthor(v *string) *BookUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *BookUpdate) ClearAuthor() *BookUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// SetCountry sets the "country" field.
func (_u *BookUpdate) SetCountry(v string) *BookUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCountry(v *string) *BookUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *BookUpdate) ClearCountry() *BookUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetTranslator sets the "translator" field.
func (_u *BookUpdate) SetTranslator(v string) *BookUpdate {
	_u.mutation.SetTranslator(v)
	return _u
}

// SetNillableTranslator sets the "translator" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTranslator(v *string) *BookUpdate {
	if v != nil {
		_u.SetTranslator(*v)
	}
	return _u
}

// ClearTranslator clears the value of the "translator" field.
func (_u *BookUpdate) ClearTranslator() *BookUpdate {
	_u.mutation.ClearTranslator()
	return _u
}

// SetPublisher sets the "publisher" field.
func (_u *BookUpdate) SetPublisher(v string) *BookUpdate {
	_u.mutation.SetPublisher(v)
	return _u
}

// SetNillablePublisher sets the "publisher" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePublisher(v *string) *BookUpdate {
	if v != nil {
		_u.SetPublisher(*v)
	}
	return _u
}

// ClearPublisher clears the value of the "publisher" field.
func (_u *BookUpdate) ClearPublisher() *BookUpdate {
	_u.mutation.ClearPublisher()
	return _u
}

// SetPubDate sets the "pub_date" field.
func (_u *BookUpdate) SetPubDate(v string) *BookUpdate {
	_u.mutation.SetPubDate(v)
	return _u
}

// SetNillablePubDate sets the "pub_date" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePubDate(v *string) *BookUpdate {
	if v != nil {
		_u.SetPubDate(*v)
	}
	return _u
}

// ClearPubDate clears the value of the "pub_date" field.
func (_u *BookUpdate) ClearPubDate() *BookUpdate {
	_u.mutation.ClearPubDate()
	return _u
}

// SetPrice sets the "price" field.
func (_u *BookUpdate) SetPrice(v string) *BookUpdate {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BookUpdate) SetNillablePrice(v *string) *BookUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// ClearPrice clears the value of the "price" field.
func (_u *BookUpdate) ClearPrice() *BookUpdate {
	_u.mutation.ClearPrice()
	return _u
}

// SetRating sets the "rating" field.
func (_u *BookUpdate) SetRating(v int) *BookUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *BookUpdate) SetNillableRating(v *int) *BookUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *BookUpdate) AddRating(v int) *BookUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// ClearRating clears the value of the "rating" field.
func (_u *BookUpdate) ClearRating() *BookUpdate {
	_u.mutation.ClearRating()
	return _u
}

// SetReadDate sets the "read_date" field.
func (_u *BookUpdate) SetReadDate(v string) *BookUpdate {
	_u.mutation.SetReadDate(v)
	return _u
}

// SetNillableReadDate sets the "read_date" field if the given value is not nil.
func (_u *BookUpdate) SetNillableReadDate(v *string) *BookUpdate {
	if v != nil {
		_u.SetReadDate(*v)
	}
	return _u
}

// ClearReadDate clears the value of the "read_date" field.
func (_u *BookUpdate) ClearReadDate() *BookUpdate {
	_u.mutation.ClearReadDate()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BookUpdate) SetStatus(v string) *BookUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BookUpdate) SetNillableStatus(v *string) *BookUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *BookUpdate) ClearStatus() *BookUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetTags sets the "tags" field.
func (_u *BookUpdate) SetTags(v string) *BookUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTags(v *string) *BookUpdate {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *BookUpdate) ClearTags() *BookUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetComment sets the "comment" field.
func (_u *BookUpdate) SetComment(v string) *BookUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *BookUpdate) SetNillableComment(v *string) *BookUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *BookUpdate) ClearComment() *BookUpdate {
	_u.mutation.ClearComment()
	return _u
}

// SetExternal sets the "external" field.
func (_u *BookUpdate) SetExternal(v string) *BookUpdate {
	_u.mutation.SetExternal(v)
	return _u
}

// SetNillableExternal sets the "external" field if the given value is not nil.
func (_u *BookUpdate) SetNillableExternal(v *string) *BookUpdate {
	if v != nil {
		_u.SetExternal(*v)
	}
	return _u
}

// ClearExternal clears the value of the "external" field.
func (_u *BookUpdate) ClearExternal() *BookUpdate {
	_u.mutation.ClearExternal()
	return _u
}

// SetScrapedAt sets the "scraped_at" field.
func (_u *BookUpdate) SetScrapedAt(v time.Time) *BookUpdate {
	_u.mutation.SetScrapedAt(v)
	return _u
}

// SetNillableScrapedAt sets the "scraped_at" field if the given value is not nil.
func (_u *BookUpdate) SetNillableScrapedAt(v *time.Time) *BookUpdate {
	if v != nil {
		_u.SetScrapedAt(*v)
	}
	return _u
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdate) Mutation() *BookMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(book.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(book.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlatformID(); ok {
		_spec.SetField(book.FieldPlatformID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlatformID(); ok {
		_spec.AddField(book.FieldPlatformID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(book.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(book.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(book.FieldCover, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(book.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(book.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(book.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.Translator(); ok {
		_spec.SetField(book.FieldTranslator, field.TypeString, value)
	}
	if _u.mutation.TranslatorCleared() {
		_spec.ClearField(book.FieldTranslator, field.TypeString)
	}
	if value, ok := _u.mutation.Publisher(); ok {
		_spec.SetField(book.FieldPublisher, field.TypeString, value)
	}
	if _u.mutation.PublisherCleared() {
		_spec.ClearField(book.FieldPublisher, field.TypeString)
	}
	if value, ok := _u.mutation.PubDate(); ok {
		_spec.SetField(book.FieldPubDate, field.TypeString, value)
	}
	if _u.mutation.PubDateCleared() {
		_spec.ClearField(book.FieldPubDate, field.TypeString)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(book.FieldPrice, field.TypeString, value)
	}
	if _u.mutation.PriceCleared() {
		_spec.ClearField(book.FieldPrice, field.TypeString)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(book.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(book.FieldRating, field.TypeInt, value)
	}
	if _u.mutation.RatingCleared() {
		_spec.ClearField(book.FieldRating, field.TypeInt)
	}
	if value, ok := _u.mutation.ReadDate(); ok {
		_spec.SetField(book.FieldReadDate, field.TypeString, value)
	}
	if _u.mutation.ReadDateCleared() {
		_spec.ClearField(book.FieldReadDate, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(book.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(book.FieldStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(book.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(book.FieldTags, field.TypeString)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(book.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(book.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.External(); ok {
		_spec.SetField(book.FieldExternal, field.TypeString, value)
	}
	if _u.mutation.ExternalCleared() {
		_spec.ClearField(book.FieldExternal, field.TypeString)
	}
	if value, ok := _u.mutation.ScrapedAt(); ok {
		_spec.SetField(book.FieldScrapedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetUserID sets the "user_id" field.
func (_u *BookUpdateOne) SetUserID(v int64) *BookUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableUserID(v *int64) *BookUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *BookUpdateOne) AddUserID(v int64) *BookUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *BookUpdateOne) SetPlatformID(v int) *BookUpdateOne {
	_u.mutation.ResetPlatformID()
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePlatformID(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// AddPlatformID adds value to the "platform_id" field.
func (_u *BookUpdateOne) AddPlatformID(v int) *BookUpdateOne {
	_u.mutation.AddPlatformID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdateOne) SetTitle(v string) *BookUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTitle(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *BookUpdateOne) SetURL(v string) *BookUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableURL(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetCover sets the "cover" field.
func (_u *BookUpdateOne) SetCover(v string) *BookUpdateOne {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCover(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *BookUpdateOne) ClearCover() *BookUpdateOne {
	_u.mutation.ClearCover()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *BookUpdateOne) SetAuthor(v string) *BookUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableAuthor(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *BookUpdateOne) ClearAuthor() *BookUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// SetCountry sets the "country" field.
func (_u *BookUpdateOne) SetCountry(v string) *BookUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCountry(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *BookUpdateOne) ClearCountry() *BookUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetTranslator sets the "translator" field.
func (_u *BookUpdateOne) SetTranslator(v string) *BookUpdateOne {
	_u.mutation.SetTranslator(v)
	return _u
}

// SetNillableTranslator sets the "translator" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTranslator(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTranslator(*v)
	}
	return _u
}

// ClearTranslator clears the value of the "translator" field.
func (_u *BookUpdateOne) ClearTranslator() *BookUpdateOne {
	_u.mutation.ClearTranslator()
	return _u
}

// SetPublisher sets the "publisher" field.
func (_u *BookUpdateOne) SetPublisher(v string) *BookUpdateOne {
	_u.mutation.SetPublisher(v)
	return _u
}

// SetNillablePublisher sets the "publisher" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePublisher(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetPublisher(*v)
	}
	return _u
}

// ClearPublisher clears the value of the "publisher" field.
func (_u *BookUpdateOne) ClearPublisher() *BookUpdateOne {
	_u.mutation.ClearPublisher()
	return _u
}

// SetPubDate sets the "pub_date" field.
func (_u *BookUpdateOne) SetPubDate(v string) *BookUpdateOne {
	_u.mutation.SetPubDate(v)
	return _u
}

// SetNillablePubDate sets the "pub_date" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePubDate(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetPubDate(*v)
	}
	return _u
}

// ClearPubDate clears the value of the "pub_date" field.
func (_u *BookUpdateOne) ClearPubDate() *BookUpdateOne {
	_u.mutation.ClearPubDate()
	return _u
}

// SetPrice sets the "price" field.
func (_u *BookUpdateOne) SetPrice(v string) *BookUpdateOne {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillablePrice(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// ClearPrice clears the value of the "price" field.
func (_u *BookUpdateOne) ClearPrice() *BookUpdateOne {
	_u.mutation.ClearPrice()
	return _u
}

// SetRating sets the "rating" field.
func (_u *BookUpdateOne) SetRating(v int) *BookUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableRating(v *int) *BookUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *BookUpdateOne) AddRating(v int) *BookUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// ClearRating clears the value of the "rating" field.
func (_u *BookUpdateOne) ClearRating() *BookUpdateOne {
	_u.mutation.ClearRating()
	return _u
}

// SetReadDate sets the "read_date" field.
func (_u *BookUpdateOne) SetReadDate(v string) *BookUpdateOne {
	_u.mutation.SetReadDate(v)
	return _u
}

// SetNillableReadDate sets the "read_date" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableReadDate(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetReadDate(*v)
	}
	return _u
}

// ClearReadDate clears the value of the "read_date" field.
func (_u *BookUpdateOne) ClearReadDate() *BookUpdateOne {
	_u.mutation.ClearReadDate()
	return _u
}

// SetStatus sets the "status" field.
func (_u *BookUpdateOne) SetStatus(v string) *BookUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableStatus(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *BookUpdateOne) ClearStatus() *BookUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetTags sets the "tags" field.
func (_u *BookUpdateOne) SetTags(v string) *BookUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTags(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *BookUpdateOne) ClearTags() *BookUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetComment sets the "comment" field.
func (_u *BookUpdateOne) SetComment(v string) *BookUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableComment(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *BookUpdateOne) ClearComment() *BookUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// SetExternal sets the "external" field.
func (_u *BookUpdateOne) SetExternal(v string) *BookUpdateOne {
	_u.mutation.SetExternal(v)
	return _u
}

// SetNillableExternal sets the "external" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableExternal(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetExternal(*v)
	}
	return _u
}

// ClearExternal clears the value of the "external" field.
func (_u *BookUpdateOne) ClearExternal() *BookUpdateOne {
	_u.mutation.ClearExternal()
	return _u
}

// SetScrapedAt sets the "scraped_at" field.
func (_u *BookUpdateOne) SetScrapedAt(v time.Time) *BookUpdateOne {
	_u.mutation.SetScrapedAt(v)
	return _u
}

// SetNillableScrapedAt sets the "scraped_at" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableScrapedAt(v *time.Time) *BookUpdateOne {
	if v != nil {
		_u.SetScrapedAt(*v)
	}
	return _u
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdateOne) Mutation() *BookMutation {
	return _u.mutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Book entity.
func (_u *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(book.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(book.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlatformID(); ok {
		_spec.SetField(book.FieldPlatformID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlatformID(); ok {
		_spec.AddField(book.FieldPlatformID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(book.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(book.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(book.FieldCover, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(book.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(book.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(book.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(book.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.Translator(); ok {
		_spec.SetField(book.FieldTranslator, field.TypeString, value)
	}
	if _u.mutation.TranslatorCleared() {
		_spec.ClearField(book.FieldTranslator, field.TypeString)
	}
	if value, ok := _u.mutation.Publisher(); ok {
		_spec.SetField(book.FieldPublisher, field.TypeString, value)
	}
	if _u.mutation.PublisherCleared() {
		_spec.ClearField(book.FieldPublisher, field.TypeString)
	}
	if value, ok := _u.mutation.PubDate(); ok {
		_spec.SetField(book.FieldPubDate, field.TypeString, value)
	}
	if _u.mutation.PubDateCleared() {
		_spec.ClearField(book.FieldPubDate, field.TypeString)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(book.FieldPrice, field.TypeString, value)
	}
	if _u.mutation.PriceCleared() {
		_spec.ClearField(book.FieldPrice, field.TypeString)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(book.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(book.FieldRating, field.TypeInt, value)
	}
	if _u.mutation.RatingCleared() {
		_spec.ClearField(book.FieldRating, field.TypeInt)
	}
	if value, ok := _u.mutation.ReadDate(); ok {
		_spec.SetField(book.FieldReadDate, field.TypeString, value)
	}
	if _u.mutation.ReadDateCleared() {
		_spec.ClearField(book.FieldReadDate, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(book.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(book.FieldStatus, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(book.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(book.FieldTags, field.TypeString)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(book.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(book.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.External(); ok {
		_spec.SetField(book.FieldExternal, field.TypeString, value)
	}
	if _u.mutation.ExternalCleared() {
		_spec.ClearField(book.FieldExternal, field.TypeString)
	}
	if value, ok := _u.mutation.ScrapedAt(); ok {
		_spec.SetField(book.FieldScrapedAt, field.TypeTime, value)
	}
	_node = &Book{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
