// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lifeink-ai/backend/ent/bookmark"
)

// BookmarkCreate is the builder for creating a Bookmark entity.
type BookmarkCreate struct {
	config
	mutation *BookmarkMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *BookmarkCreate) SetUserID(v int64) *BookmarkCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPlatformID sets the "platform_id" field.
func (_c *BookmarkCreate) SetPlatformID(v int) *BookmarkCreate {
	_c.mutation.SetPlatformID(v)
	return _c
}

// SetBookID sets the "book_id" field.
func (_c *BookmarkCreate) SetBookID(v string) *BookmarkCreate {
	_c.mutation.SetBookID(v)
	return _c
}

// SetBookTitle sets the "book_title" field.
func (_c *BookmarkCreate) SetBookTitle(v string) *BookmarkCreate {
	_c.mutation.SetBookTitle(v)
	return _c
}

// SetNillableBookTitle sets the "book_title" field if the given value is not nil.
func (_c *BookmarkCreate) SetNillableBookTitle(v *string) *BookmarkCreate {
	if v != nil {
		_c.SetBookTitle(*v)
	}
	return _c
}

// SetMarkText sets the "mark_text" field.
func (_c *BookmarkCreate) SetMarkText(v string) *BookmarkCreate {
	_c.mutation.SetMarkText(v)
	return _c
}

// SetChapterName sets the "chapter_name" field.
func (_c *BookmarkCreate) SetChapterName(v string) *BookmarkCreate {
	_c.mutation.SetChapterName(v)
	return _c
}

// SetNillableChapterName sets the "chapter_name" field if the given value is not nil.
func (_c *BookmarkCreate) SetNillableChapterName(v *string) *BookmarkCreate {
	if v != nil {
		_c.SetChapterName(*v)
	}
	return _c
}

// SetChapterIdx sets the "chapter_idx" field.
func (_c *BookmarkCreate) SetChapterIdx(v int) *BookmarkCreate {
	_c.mutation.SetChapterIdx(v)
	return _c
}

// SetNillableChapterIdx sets the "chapter_idx" field if the given value is not nil.
func (_c *BookmarkCreate) SetNillableChapterIdx(v *int) *BookmarkCreate {
	if v != nil {
		_c.SetChapterIdx(*v)
	}
	return _c
}

// SetStyle sets the "style" field.
func (_c *BookmarkCreate) SetStyle(v int) *BookmarkCreate {
	_c.mutation.SetStyle(v)
	return _c
}

// SetNillableStyle sets the "style" field if the given value is not nil.
func (_c *BookmarkCreate) SetNillableStyle(v *int) *BookmarkCreate {
	if v != nil {
		_c.SetStyle(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *BookmarkCreate) SetCreateTime(v int64) *BookmarkCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *BookmarkCreate) SetNillableCreateTime(v *int64) *BookmarkCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetBookmarkID sets the "bookmark_id" field.
func (_c *BookmarkCreate) SetBookmarkID(v string) *BookmarkCreate {
	_c.mutation.SetBookmarkID(v)
	return _c
}

// SetNillableBookmarkID sets the "bookmark_id" field if the given value is not nil.
func (_c *BookmarkCreate) SetNillableBookmarkID(v *string) *BookmarkCreate {
	if v != nil {
		_c.SetBookmarkID(*v)
	}
	return _c
}

// SetScrapedAt sets the "scraped_at" field.
func (_c *BookmarkCreate) SetScrapedAt(v time.Time) *BookmarkCreate {
	_c.mutation.SetScrapedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BookmarkCreate) SetID(v int64) *BookmarkCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BookmarkMutation object of the builder.
func (_c *BookmarkCreate) Mutation() *BookmarkMutation {
	return _c.mutation
}

// Save creates the Bookmark in the database.
func (_c *BookmarkCreate) Save(ctx context.Context) (*Bookmark, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BookmarkCreate) SaveX(ctx context.Context) *Bookmark {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookmarkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookmarkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BookmarkCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Bookmark.user_id"`)}
	}
	if _, ok := _c.mutation.PlatformID(); !ok {
		return &ValidationError{Name: "platform_id", err: errors.New(`ent: missing required field "Bookmark.platform_id"`)}
	}
	if _, ok := _c.mutation.BookID(); !ok {
		return &ValidationError{Name: "book_id", err: errors.New(`ent: missing required field "Bookmark.book_id"`)}
	}
	if _, ok := _c.mutation.MarkText(); !ok {
		return &ValidationError{Name: "mark_text", err: errors.New(`ent: missing required field "Bookmark.mark_text"`)}
	}
	if _, ok := _c.mutation.ScrapedAt(); !ok {
		return &ValidationError{Name: "scraped_at", err: errors.New(`ent: missing required field "Bookmark.scraped_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := bookmark.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Bookmark.id": %w`, err)}
		}
	}
	return nil
}

func (_c *BookmarkCreate) sqlSave(ctx context.Context) (*Bookmark, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BookmarkCreate) createSpec() (*Bookmark, *sqlgraph.CreateSpec) {
	var (
		_node = &Bookmark{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bookmark.Table, sqlgraph.NewFieldSpec(bookmark.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(bookmark.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PlatformID(); ok {
		_spec.SetField(bookmark.FieldPlatformID, field.TypeInt, value)
		_node.PlatformID = value
	}
	if value, ok := _c.mutation.BookID(); ok {
		_spec.SetField(bookmark.FieldBookID, field.TypeString, value)
		_node.BookID = value
	}
	if value, ok := _c.mutation.BookTitle(); ok {
		_spec.SetField(bookmark.FieldBookTitle, field.TypeString, value)
		_node.BookTitle = &value
	}
	if value, ok := _c.mutation.MarkText(); ok {
		_spec.SetField(bookmark.FieldMarkText, field.TypeString, value)
		_node.MarkText = value
	}
	if value, ok := _c.mutation.ChapterName(); ok {
		_spec.SetField(bookmark.FieldChapterName, field.TypeString, value)
		_node.ChapterName = &value
	}
	if value, ok := _c.mutation.ChapterIdx(); ok {
		_spec.SetField(bookmark.FieldChapterIdx, field.TypeInt, value)
		_node.ChapterIdx = &value
	}
	if value, ok := _c.mutation.Style(); ok {
		_spec.SetField(bookmark.FieldStyle, field.TypeInt, value)
		_node.Style = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(bookmark.FieldCreateTime, field.TypeInt64, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.BookmarkID(); ok {
		_spec.SetField(bookmark.FieldBookmarkID, field.TypeString, value)
		_node.BookmarkID = &value
	}
	if value, ok := _c.mutation.ScrapedAt(); ok {
		_spec.SetField(bookmark.FieldScrapedAt, field.TypeTime, value)
		_node.ScrapedAt = value
	}
	return _node, _spec
}

// BookmarkCreateBulk is the builder for creating many Bookmark entities in bulk.
type BookmarkCreateBulk struct {
	config
	err      error
	builders []*BookmarkCreate
}

// Save creates the Bookmark entities in the database.
func (_c *BookmarkCreateBulk) Save(ctx context.Context) ([]*Bookmark, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Bookmark, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BookmarkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BookmarkCreateBulk) SaveX(ctx context.Context) []*Bookmark {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookmarkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookmarkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
