// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lifeink-ai/backend/ent/book"
)

// Book is the model entity for the Book schema.
type Book struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PlatformID holds the value of the "platform_id" field.
	PlatformID int `json:"platform_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Cover holds the value of the "cover" field.
	Cover *string `json:"cover,omitempty"`
	// Author holds the value of the "author" field.
	Author *string `json:"author,omitempty"`
	// Country holds the value of the "country" field.
	Country *string `json:"country,omitempty"`
	// Translator holds the value of the "translator" field.
	Translator *string `json:"translator,omitempty"`
	// Publisher holds the value of the "publisher" field.
	Publisher *string `json:"publisher,omitempty"`
	// PubDate holds the value of the "pub_date" field.
	PubDate *string `json:"pub_date,omitempty"`
	// Price holds the value of the "price" field.
	Price *string `json:"price,omitempty"`
	// Rating holds the value of the "rating" field.
	Rating *int `json:"rating,omitempty"`
	// ReadDate holds the value of the "read_date" field.
	ReadDate *string `json:"read_date,omitempty"`
	// Status holds the value of the "status" field.
	Status *string `json:"status,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags *string `json:"tags,omitempty"`
	// Comment holds the value of the "comment" field.
	Comment *string `json:"comment,omitempty"`
	// External holds the value of the "external" field.
	External *string `json:"external,omitempty"`
	// ScrapedAt holds the value of the "scraped_at" field.
	ScrapedAt    time.Time `json:"scraped_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Book) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case book.FieldID, book.FieldUserID, book.FieldPlatformID, book.FieldRating:
			values[i] = new(sql.NullInt64)
		case book.FieldTitle, book.FieldURL, book.FieldCover, book.FieldAuthor, book.FieldCountry, book.FieldTranslator, book.FieldPublisher, book.FieldPubDate, book.FieldPrice, book.FieldReadDate, book.FieldStatus, book.FieldTags, book.FieldComment, book.FieldExternal:
			values[i] = new(sql.NullString)
		case book.FieldScrapedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Book fields.
func (_m *Book) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case book.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case book.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case book.FieldPlatformID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field platform_id", values[i])
			} else if value.Valid {
				_m.PlatformID = int(value.Int64)
			}
		case book.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case book.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case book.FieldCover:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover", values[i])
			} else if value.Valid {
				_m.Cover = new(string)
				*_m.Cover = value.String
			}
		case book.FieldAuthor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author", values[i])
			} else if value.Valid {
				_m.Author = new(string)
				*_m.Author = value.String
			}
		case book.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = new(string)
				*_m.Country = value.String
			}
		case book.FieldTranslator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field translator", values[i])
			} else if value.Valid {
				_m.Translator = new(string)
				*_m.Translator = value.String
			}
		case book.FieldPublisher:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field publisher", values[i])
			} else if value.Valid {
				_m.Publisher = new(string)
				*_m.Publisher = value.String
			}
		case book.FieldPubDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pub_date", values[i])
			} else if value.Valid {
				_m.PubDate = new(string)
				*_m.PubDate = value.String
			}
		case book.FieldPrice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = new(string)
				*_m.Price = value.String
			}
		case book.FieldRating:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = new(int)
				*_m.Rating = int(value.Int64)
			}
		case book.FieldReadDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field read_date", values[i])
			} else if value.Valid {
				_m.ReadDate = new(string)
				*_m.ReadDate = value.String
			}
		case book.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = new(string)
				*_m.Status = value.String
			}
		case book.FieldTags:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value.Valid {
				_m.Tags = new(string)
				*_m.Tags = value.String
			}
		case book.FieldComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment", values[i])
			} else if value.Valid {
				_m.Comment = new(string)
				*_m.Comment = value.String
			}
		case book.FieldExternal:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external", values[i])
			} else if value.Valid {
				_m.External = new(string)
				*_m.External = value.String
			}
		case book.FieldScrapedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scraped_at", values[i])
			} else if value.Valid {
				_m.ScrapedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Book.
// This includes values selected through modifiers, order, etc.
func (_m *Book) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Book.
// Note that you need to call Book.Unwrap() before calling this method if this Book
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Book) Update() *BookUpdateOne {
	return NewBookClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Book entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Book) Unwrap() *Book {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Book is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Book) String() string {
	var builder strings.Builder
	builder.WriteString("Book(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("platform_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlatformID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	if v := _m.Cover; v != nil {
		builder.WriteString("cover=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Author; v != nil {
		builder.WriteString("author=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Country; v != nil {
		builder.WriteString("country=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Translator; v != nil {
		builder.WriteString("translator=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Publisher; v != nil {
		builder.WriteString("publisher=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PubDate; v != nil {
		builder.WriteString("pub_date=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Price; v != nil {
		builder.WriteString("price=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Rating; v != nil {
		builder.WriteString("rating=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReadDate; v != nil {
		builder.WriteString("read_date=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Status; v != nil {
		builder.WriteString("status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Tags; v != nil {
		builder.WriteString("tags=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Comment; v != nil {
		builder.WriteString("comment=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.External; v != nil {
		builder.WriteString("external=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("scraped_at=")
	builder.WriteString(_m.ScrapedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Books is a parsable slice of Book.
type Books []*Book
