// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lifeink-ai/backend/ent/communitymeta"
)

// CommunityMetaCreate is the builder for creating a CommunityMeta entity.
type CommunityMetaCreate struct {
	config
	mutation *CommunityMetaMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *CommunityMetaCreate) SetUserID(v int64) *CommunityMetaCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPlatformID sets the "platform_id" field.
func (_c *CommunityMetaCreate) SetPlatformID(v int) *CommunityMetaCreate {
	_c.mutation.SetPlatformID(v)
	return _c
}

// SetBound sets the "bound" field.
func (_c *CommunityMetaCreate) SetBound(v int) *CommunityMetaCreate {
	_c.mutation.SetBound(v)
	return _c
}

// SetNillableBound sets the "bound" field if the given value is not nil.
func (_c *CommunityMetaCreate) SetNillableBound(v *int) *CommunityMetaCreate {
	if v != nil {
		_c.SetBound(*v)
	}
	return _c
}

// SetCommunityUserID sets the "community_user_id" field.
func (_c *CommunityMetaCreate) SetCommunityUserID(v string) *CommunityMetaCreate {
	_c.mutation.SetCommunityUserID(v)
	return _c
}

// SetNillableCommunityUserID sets the "community_user_id" field if the given value is not nil.
func (_c *CommunityMetaCreate) SetNillableCommunityUserID(v *string) *CommunityMetaCreate {
	if v != nil {
		_c.SetCommunityUserID(*v)
	}
	return _c
}

// SetProfileJSON sets the "profile_json" field.
func (_c *CommunityMetaCreate) SetProfileJSON(v string) *CommunityMetaCreate {
	_c.mutation.SetProfileJSON(v)
	return _c
}

// SetNillableProfileJSON sets the "profile_json" field if the given value is not nil.
func (_c *CommunityMetaCreate) SetNillableProfileJSON(v *string) *CommunityMetaCreate {
	if v != nil {
		_c.SetProfileJSON(*v)
	}
	return _c
}

// SetSessionStateJSON sets the "session_state_json" field.
func (_c *CommunityMetaCreate) SetSessionStateJSON(v string) *CommunityMetaCreate {
	_c.mutation.SetSessionStateJSON(v)
	return _c
}

// SetNillableSessionStateJSON sets the "session_state_json" field if the given value is not nil.
func (_c *CommunityMetaCreate) SetNillableSessionStateJSON(v *string) *CommunityMetaCreate {
	if v != nil {
		_c.SetSessionStateJSON(*v)
	}
	return _c
}

// SetSessionExpiresAt sets the "session_expires_at" field.
func (_c *CommunityMetaCreate) SetSessionExpiresAt(v string) *CommunityMetaCreate {
	_c.mutation.SetSessionExpiresAt(v)
	return _c
}

// SetNillableSessionExpiresAt sets the "session_expires_at" field if the given value is not nil.
func (_c *CommunityMetaCreate) SetNillableSessionExpiresAt(v *string) *CommunityMetaCreate {
	if v != nil {
		_c.SetSessionExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CommunityMetaCreate) SetCreatedAt(v time.Time) *CommunityMetaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CommunityMetaCreate) SetUpdatedAt(v time.Time) *CommunityMetaCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CommunityMetaCreate) SetID(v int64) *CommunityMetaCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CommunityMetaMutation object of the builder.
func (_c *CommunityMetaCreate) Mutation() *CommunityMetaMutation {
	return _c.mutation
}

// Save creates the CommunityMeta in the database.
func (_c *CommunityMetaCreate) Save(ctx context.Context) (*CommunityMeta, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CommunityMetaCreate) SaveX(ctx context.Context) *CommunityMeta {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommunityMetaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommunityMetaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CommunityMetaCreate) defaults() {
	if _, ok := _c.mutation.Bound(); !ok {
		v := communitymeta.DefaultBound
		_c.mutation.SetBound(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CommunityMetaCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CommunityMeta.user_id"`)}
	}
	if _, ok := _c.mutation.PlatformID(); !ok {
		return &ValidationError{Name: "platform_id", err: errors.New(`ent: missing required field "CommunityMeta.platform_id"`)}
	}
	if _, ok := _c.mutation.Bound(); !ok {
		return &ValidationError{Name: "bound", err: errors.New(`ent: missing required field "CommunityMeta.bound"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CommunityMeta.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CommunityMeta.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := communitymeta.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "CommunityMeta.id": %w`, err)}
		}
	}
	return nil
}

func (_c *CommunityMetaCreate) sqlSave(ctx context.Context) (*CommunityMeta, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CommunityMetaCreate) createSpec() (*CommunityMeta, *sqlgraph.CreateSpec) {
	var (
		_node = &CommunityMeta{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(communitymeta.Table, sqlgraph.NewFieldSpec(communitymeta.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(communitymeta.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PlatformID(); ok {
		_spec.SetField(communitymeta.FieldPlatformID, field.TypeInt, value)
		_node.PlatformID = value
	}
	if value, ok := _c.mutation.Bound(); ok {
		_spec.SetField(communitymeta.FieldBound, field.TypeInt, value)
		_node.Bound = value
	}
	if value, ok := _c.mutation.CommunityUserID(); ok {
		_spec.SetField(communitymeta.FieldCommunityUserID, field.TypeString, value)
		_node.CommunityUserID = &value
	}
	if value, ok := _c.mutation.ProfileJSON(); ok {
		_spec.SetField(communitymeta.FieldProfileJSON, field.TypeString, value)
		_node.ProfileJSON = &value
	}
	if value, ok := _c.mutation.SessionStateJSON(); ok {
		_spec.SetField(communitymeta.FieldSessionStateJSON, field.TypeString, value)
		_node.SessionStateJSON = &value
	}
	if value, ok := _c.mutation.SessionExpiresAt(); ok {
		_spec.SetField(communitymeta.FieldSessionExpiresAt, field.TypeString, value)
		_node.SessionExpiresAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(communitymeta.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(communitymeta.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CommunityMetaCreateBulk is the builder for creating many CommunityMeta entities in bulk.
type CommunityMetaCreateBulk struct {
	config
	err      error
	builders []*CommunityMetaCreate
}

// Save creates the CommunityMeta entities in the database.
func (_c *CommunityMetaCreateBulk) Save(ctx context.Context) ([]*CommunityMeta, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CommunityMeta, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommunityMetaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CommunityMetaCreateBulk) SaveX(ctx context.Context) []*CommunityMeta {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommunityMetaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommunityMetaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
