// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lifeink-ai/backend/ent/communitymeta"
	"github.com/lifeink-ai/backend/ent/predicate"
)

// CommunityMetaDelete is the builder for deleting a CommunityMeta entity.
type CommunityMetaDelete struct {
	config
	hooks    []Hook
	mutation *CommunityMetaMutation
}

// Where appends a list predicates to the CommunityMetaDelete builder.
func (_d *CommunityMetaDelete) Where(ps ...predicate.CommunityMeta) *CommunityMetaDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CommunityMetaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CommunityMetaDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CommunityMetaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(communitymeta.Table, sqlgraph.NewFieldSpec(communitymeta.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CommunityMetaDeleteOne is the builder for deleting a single CommunityMeta entity.
type CommunityMetaDeleteOne struct {
	_d *CommunityMetaDelete
}

// Where appends a list predicates to the CommunityMetaDelete builder.
func (_d *CommunityMetaDeleteOne) Where(ps ...predicate.CommunityMeta) *CommunityMetaDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CommunityMetaDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{communitymeta.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CommunityMetaDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
