// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lifeink-ai/backend/ent/flomomemo"
	"github.com/lifeink-ai/backend/ent/predicate"
)

// FlomoMemoUpdate is the builder for updating FlomoMemo entities.
type FlomoMemoUpdate struct {
	config
	hooks    []Hook
	mutation *FlomoMemoMutation
}

// Where appends a list predicates to the FlomoMemoUpdate builder.
func (_u *FlomoMemoUpdate) Where(ps ...predicate.FlomoMemo) *FlomoMemoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FlomoMemoUpdate) SetUserID(v int64) *FlomoMemoUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FlomoMemoUpdate) SetNillableUserID(v *int64) *FlomoMemoUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *FlomoMemoUpdate) AddUserID(v int64) *FlomoMemoUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *FlomoMemoUpdate) SetPlatformID(v int) *FlomoMemoUpdate {
	_u.mutation.ResetPlatformID()
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *FlomoMemoUpdate) SetNillablePlatformID(v *int) *FlomoMemoUpdate {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// AddPlatformID adds value to the "platform_id" field.
func (_u *FlomoMemoUpdate) AddPlatformID(v int) *FlomoMemoUpdate {
	_u.mutation.AddPlatformID(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *FlomoMemoUpdate) SetContent(v string) *FlomoMemoUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *FlomoMemoUpdate) SetNillableContent(v *string) *FlomoMemoUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *FlomoMemoUpdate) SetTags(v string) *FlomoMemoUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *FlomoMemoUpdate) SetNillableTags(v *string) *FlomoMemoUpdate {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *FlomoMemoUpdate) ClearTags() *FlomoMemoUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetFiles sets the "files" field.
func (_u *FlomoMemoUpdate) SetFiles(v string) *FlomoMemoUpdate {
	_u.mutation.SetFiles(v)
	return _u
}

// SetNillableFiles sets the "files" field if the given value is not nil.
func (_u *FlomoMemoUpdate) SetNillableFiles(v *string) *FlomoMemoUpdate {
	if v != nil {
		_u.SetFiles(*v)
	}
	return _u
}

// ClearFiles clears the value of the "files" field.
func (_u *FlomoMemoUpdate) ClearFiles() *FlomoMemoUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// SetMemoCreatedAt sets the "memo_created_at" field.
func (_u *FlomoMemoUpdate) SetMemoCreatedAt(v string) *FlomoMemoUpdate {
	_u.mutation.SetMemoCreatedAt(v)
	return _u
}

// SetNillableMemoCreatedAt sets the "memo_created_at" field if the given value is not nil.
func (_u *FlomoMemoUpdate) SetNillableMemoCreatedAt(v *string) *FlomoMemoUpdate {
	if v != nil {
		_u.SetMemoCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FlomoMemoUpdate) SetUpdatedAt(v time.Time) *FlomoMemoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FlomoMemoUpdate) SetNillableUpdatedAt(v *time.Time) *FlomoMemoUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetScrapedAt sets the "scraped_at" field.
func (_u *FlomoMemoUpdate) SetScrapedAt(v time.Time) *FlomoMemoUpdate {
	_u.mutation.SetScrapedAt(v)
	return _u
}

// SetNillableScrapedAt sets the "scraped_at" field if the given value is not nil.
func (_u *FlomoMemoUpdate) SetNillableScrapedAt(v *time.Time) *FlomoMemoUpdate {
	if v != nil {
		_u.SetScrapedAt(*v)
	}
	return _u
}

// Mutation returns the FlomoMemoMutation object of the builder.
func (_u *FlomoMemoUpdate) Mutation() *FlomoMemoMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FlomoMemoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlomoMemoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FlomoMemoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlomoMemoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FlomoMemoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(flomomemo.Table, flomomemo.Columns, sqlgraph.NewFieldSpec(flomomemo.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(flomomemo.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(flomomemo.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlatformID(); ok {
		_spec.SetField(flomomemo.FieldPlatformID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlatformID(); ok {
		_spec.AddField(flomomemo.FieldPlatformID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(flomomemo.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(flomomemo.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(flomomemo.FieldTags, field.TypeString)
	}
	if value, ok := _u.mutation.Files(); ok {
		_spec.SetField(flomomemo.FieldFiles, field.TypeString, value)
	}
	if _u.mutation.FilesCleared() {
		_spec.ClearField(flomomemo.FieldFiles, field.TypeString)
	}
	if value, ok := _u.mutation.MemoCreatedAt(); ok {
		_spec.SetField(flomomemo.FieldMemoCreatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flomomemo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ScrapedAt(); ok {
		_spec.SetField(flomomemo.FieldScrapedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flomomemo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FlomoMemoUpdateOne is the builder for updating a single FlomoMemo entity.
type FlomoMemoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlomoMemoMutation
}

// SetUserID sets the "user_id" field.
func (_u *FlomoMemoUpdateOne) SetUserID(v int64) *FlomoMemoUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FlomoMemoUpdateOne) SetNillableUserID(v *int64) *FlomoMemoUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *FlomoMemoUpdateOne) AddUserID(v int64) *FlomoMemoUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetPlatformID sets the "platform_id" field.
func (_u *FlomoMemoUpdateOne) SetPlatformID(v int) *FlomoMemoUpdateOne {
	_u.mutation.ResetPlatformID()
	_u.mutation.SetPlatformID(v)
	return _u
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (_u *FlomoMemoUpdateOne) SetNillablePlatformID(v *int) *FlomoMemoUpdateOne {
	if v != nil {
		_u.SetPlatformID(*v)
	}
	return _u
}

// AddPlatformID adds value to the "platform_id" field.
func (_u *FlomoMemoUpdateOne) AddPlatformID(v int) *FlomoMemoUpdateOne {
	_u.mutation.AddPlatformID(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *FlomoMemoUpdateOne) SetContent(v string) *FlomoMemoUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *FlomoMemoUpdateOne) SetNillableContent(v *string) *FlomoMemoUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *FlomoMemoUpdateOne) SetTags(v string) *FlomoMemoUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *FlomoMemoUpdateOne) SetNillableTags(v *string) *FlomoMemoUpdateOne {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *FlomoMemoUpdateOne) ClearTags() *FlomoMemoUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetFiles sets the "files" field.
func (_u *FlomoMemoUpdateOne) SetFiles(v string) *FlomoMemoUpdateOne {
	_u.mutation.SetFiles(v)
	return _u
}

// SetNillableFiles sets the "files" field if the given value is not nil.
func (_u *FlomoMemoUpdateOne) SetNillableFiles(v *string) *FlomoMemoUpdateOne {
	if v != nil {
		_u.SetFiles(*v)
	}
	return _u
}

// ClearFiles clears the value of the "files" field.
func (_u *FlomoMemoUpdateOne) ClearFiles() *FlomoMemoUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// SetMemoCreatedAt sets the "memo_created_at" field.
func (_u *FlomoMemoUpdateOne) SetMemoCreatedAt(v string) *FlomoMemoUpdateOne {
	_u.mutation.SetMemoCreatedAt(v)
	return _u
}

// SetNillableMemoCreatedAt sets the "memo_created_at" field if the given value is not nil.
func (_u *FlomoMemoUpdateOne) SetNillableMemoCreatedAt(v *string) *FlomoMemoUpdateOne {
	if v != nil {
		_u.SetMemoCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FlomoMemoUpdateOne) SetUpdatedAt(v time.Time) *FlomoMemoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FlomoMemoUpdateOne) SetNillableUpdatedAt(v *time.Time) *FlomoMemoUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetScrapedAt sets the "scraped_at" field.
func (_u *FlomoMemoUpdateOne) SetScrapedAt(v time.Time) *FlomoMemoUpdateOne {
	_u.mutation.SetScrapedAt(v)
	return _u
}

// SetNillableScrapedAt sets the "scraped_at" field if the given value is not nil.
func (_u *FlomoMemoUpdateOne) SetNillableScrapedAt(v *time.Time) *FlomoMemoUpdateOne {
	if v != nil {
		_u.SetScrapedAt(*v)
	}
	return _u
}

// Mutation returns the FlomoMemoMutation object of the builder.
func (_u *FlomoMemoUpdateOne) Mutation() *FlomoMemoMutation {
	return _u.mutation
}

// Where appends a list predicates to the FlomoMemoUpdate builder.
func (_u *FlomoMemoUpdateOne) Where(ps ...predicate.FlomoMemo) *FlomoMemoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FlomoMemoUpdateOne) Select(field string, fields ...string) *FlomoMemoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FlomoMemo entity.
func (_u *FlomoMemoUpdateOne) Save(ctx context.Context) (*FlomoMemo, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlomoMemoUpdateOne) SaveX(ctx context.Context) *FlomoMemo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FlomoMemoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlomoMemoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FlomoMemoUpdateOne) sqlSave(ctx context.Context) (_node *FlomoMemo, err error) {
	_spec := sqlgraph.NewUpdateSpec(flomomemo.Table, flomomemo.Columns, sqlgraph.NewFieldSpec(flomomemo.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FlomoMemo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flomomemo.FieldID)
		for _, f := range fields {
			if !flomomemo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flomomemo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(flomomemo.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(flomomemo.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PlatformID(); ok {
		_spec.SetField(flomomemo.FieldPlatformID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPlatformID(); ok {
		_spec.AddField(flomomemo.FieldPlatformID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(flomomemo.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(flomomemo.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(flomomemo.FieldTags, field.TypeString)
	}
	if value, ok := _u.mutation.Files(); ok {
		_spec.SetField(flomomemo.FieldFiles, field.TypeString, value)
	}
	if _u.mutation.FilesCleared() {
		_spec.ClearField(flomomemo.FieldFiles, field.TypeString)
	}
	if value, ok := _u.mutation.MemoCreatedAt(); ok {
		_spec.SetField(flomomemo.FieldMemoCreatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flomomemo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ScrapedAt(); ok {
		_spec.SetField(flomomemo.FieldScrapedAt, field.TypeTime, value)
	}
	_node = &FlomoMemo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flomomemo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
