// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lifeink-ai/backend/ent/flomomemo"
)

// FlomoMemo is the model entity for the FlomoMemo schema.
type FlomoMemo struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// PlatformID holds the value of the "platform_id" field.
	PlatformID int `json:"platform_id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags *string `json:"tags,omitempty"`
	// Files holds the value of the "files" field.
	Files *string `json:"files,omitempty"`
	// MemoCreatedAt holds the value of the "memo_created_at" field.
	MemoCreatedAt string `json:"memo_created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ScrapedAt holds the value of the "scraped_at" field.
	ScrapedAt    time.Time `json:"scraped_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FlomoMemo) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flomomemo.FieldID, flomomemo.FieldUserID, flomomemo.FieldPlatformID:
			values[i] = new(sql.NullInt64)
		case flomomemo.FieldContent, flomomemo.FieldTags, flomomemo.FieldFiles, flomomemo.FieldMemoCreatedAt:
			values[i] = new(sql.NullString)
		case flomomemo.FieldUpdatedAt, flomomemo.FieldScrapedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FlomoMemo fields.
func (_m *FlomoMemo) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flomomemo.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case flomomemo.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case flomomemo.FieldPlatformID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field platform_id", values[i])
			} else if value.Valid {
				_m.PlatformID = int(value.Int64)
			}
		case flomomemo.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case flomomemo.FieldTags:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value.Valid {
				_m.Tags = new(string)
				*_m.Tags = value.String
			}
		case flomomemo.FieldFiles:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field files", values[i])
			} else if value.Valid {
				_m.Files = new(string)
				*_m.Files = value.String
			}
		case flomomemo.FieldMemoCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field memo_created_at", values[i])
			} else if value.Valid {
				_m.MemoCreatedAt = value.String
			}
		case flomomemo.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case flomomemo.FieldScrapedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scraped_at", values[i])
			} else if value.Valid {
				_m.ScrapedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FlomoMemo.
// This includes values selected through modifiers, order, etc.
func (_m *FlomoMemo) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FlomoMemo.
// Note that you need to call FlomoMemo.Unwrap() before calling this method if this FlomoMemo
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FlomoMemo) Update() *FlomoMemoUpdateOne {
	return NewFlomoMemoClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FlomoMemo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FlomoMemo) Unwrap() *FlomoMemo {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FlomoMemo is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FlomoMemo) String() string {
	var builder strings.Builder
	builder.WriteString("FlomoMemo(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("platform_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlatformID))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	if v := _m.Tags; v != nil {
		builder.WriteString("tags=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Files; v != nil {
		builder.WriteString("files=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("memo_created_at=")
	builder.WriteString(_m.MemoCreatedAt)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("scraped_at=")
	builder.WriteString(_m.ScrapedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FlomoMemos is a parsable slice of FlomoMemo.
type FlomoMemos []*FlomoMemo
