// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lifeink-ai/backend/ent/flomomemo"
)

// FlomoMemoCreate is the builder for creating a FlomoMemo entity.
type FlomoMemoCreate struct {
	config
	mutation *FlomoMemoMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *FlomoMemoCreate) SetUserID(v int64) *FlomoMemoCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPlatformID sets the "platform_id" field.
func (_c *FlomoMemoCreate) SetPlatformID(v int) *FlomoMemoCreate {
	_c.mutation.SetPlatformID(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *FlomoMemoCreate) SetContent(v string) *FlomoMemoCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *FlomoMemoCreate) SetTags(v string) *FlomoMemoCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_c *FlomoMemoCreate) SetNillableTags(v *string) *FlomoMemoCreate {
	if v != nil {
		_c.SetTags(*v)
	}
	return _c
}

// SetFiles sets the "files" field.
func (_c *FlomoMemoCreate) SetFiles(v string) *FlomoMemoCreate {
	_c.mutation.SetFiles(v)
	return _c
}

// SetNillableFiles sets the "files" field if the given value is not nil.
func (_c *FlomoMemoCreate) SetNillableFiles(v *string) *FlomoMemoCreate {
	if v != nil {
		_c.SetFiles(*v)
	}
	return _c
}

// SetMemoCreatedAt sets the "memo_created_at" field.
func (_c *FlomoMemoCreate) SetMemoCreatedAt(v string) *FlomoMemoCreate {
	_c.mutation.SetMemoCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FlomoMemoCreate) SetUpdatedAt(v time.Time) *FlomoMemoCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetScrapedAt sets the "scraped_at" field.
func (_c *FlomoMemoCreate) SetScrapedAt(v time.Time) *FlomoMemoCreate {
	_c.mutation.SetScrapedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *FlomoMemoCreate) SetID(v int64) *FlomoMemoCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the FlomoMemoMutation object of the builder.
func (_c *FlomoMemoCreate) Mutation() *FlomoMemoMutation {
	return _c.mutation
}

// Save creates the FlomoMemo in the database.
func (_c *FlomoMemoCreate) Save(ctx context.Context) (*FlomoMemo, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FlomoMemoCreate) SaveX(ctx context.Context) *FlomoMemo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlomoMemoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlomoMemoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FlomoMemoCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "FlomoMemo.user_id"`)}
	}
	if _, ok := _c.mutation.PlatformID(); !ok {
		return &ValidationError{Name: "platform_id", err: errors.New(`ent: missing required field "FlomoMemo.platform_id"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "FlomoMemo.content"`)}
	}
	if _, ok := _c.mutation.MemoCreatedAt(); !ok {
		return &ValidationError{Name: "memo_created_at", err: errors.New(`ent: missing required field "FlomoMemo.memo_created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FlomoMemo.updated_at"`)}
	}
	if _, ok := _c.mutation.ScrapedAt(); !ok {
		return &ValidationError{Name: "scraped_at", err: errors.New(`ent: missing required field "FlomoMemo.scraped_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := flomomemo.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "FlomoMemo.id": %w`, err)}
		}
	}
	return nil
}

func (_c *FlomoMemoCreate) sqlSave(ctx context.Context) (*FlomoMemo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FlomoMemoCreate) createSpec() (*FlomoMemo, *sqlgraph.CreateSpec) {
	var (
		_node = &FlomoMemo{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(flomomemo.Table, sqlgraph.NewFieldSpec(flomomemo.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(flomomemo.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.PlatformID(); ok {
		_spec.SetField(flomomemo.FieldPlatformID, field.TypeInt, value)
		_node.PlatformID = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(flomomemo.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(flomomemo.FieldTags, field.TypeString, value)
		_node.Tags = &value
	}
	if value, ok := _c.mutation.Files(); ok {
		_spec.SetField(flomomemo.FieldFiles, field.TypeString, value)
		_node.Files = &value
	}
	if value, ok := _c.mutation.MemoCreatedAt(); ok {
		_spec.SetField(flomomemo.FieldMemoCreatedAt, field.TypeString, value)
		_node.MemoCreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(flomomemo.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ScrapedAt(); ok {
		_spec.SetField(flomomemo.FieldScrapedAt, field.TypeTime, value)
		_node.ScrapedAt = value
	}
	return _node, _spec
}

// FlomoMemoCreateBulk is the builder for creating many FlomoMemo entities in bulk.
type FlomoMemoCreateBulk struct {
	config
	err      error
	builders []*FlomoMemoCreate
}

// Save creates the FlomoMemo entities in the database.
func (_c *FlomoMemoCreateBulk) Save(ctx context.Context) ([]*FlomoMemo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FlomoMemo, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlomoMemoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FlomoMemoCreateBulk) SaveX(ctx context.Context) []*FlomoMemo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlomoMemoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlomoMemoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
