// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lifeink-ai/backend/ent/message"
	"github.com/lifeink-ai/backend/ent/predicate"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *MessageUpdate) SetSessionID(v int64) *MessageUpdate {
	_u.mutation.ResetSessionID()
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableSessionID(v *int64) *MessageUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// AddSessionID adds value to the "session_id" field.
func (_u *MessageUpdate) AddSessionID(v int64) *MessageUpdate {
	_u.mutation.AddSessionID(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdate) SetRole(v string) *MessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableRole(v *string) *MessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdate) SetContent(v string) *MessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableContent(v *string) *MessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetReasoning sets the "reasoning" field.
func (_u *MessageUpdate) SetReasoning(v string) *MessageUpdate {
	_u.mutation.SetReasoning(v)
	return _u
}

// SetNillableReasoning sets the "reasoning" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableReasoning(v *string) *MessageUpdate {
	if v != nil {
		_u.SetReasoning(*v)
	}
	return _u
}

// ClearReasoning clears the value of the "reasoning" field.
func (_u *MessageUpdate) ClearReasoning() *MessageUpdate {
	_u.mutation.ClearReasoning()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MessageUpdate) SetCreatedAt(v time.Time) *MessageUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableCreatedAt(v *time.Time) *MessageUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(message.FieldSessionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSessionID(); ok {
		_spec.AddField(message.FieldSessionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reasoning(); ok {
		_spec.SetField(message.FieldReasoning, field.TypeString, value)
	}
	if _u.mutation.ReasoningCleared() {
		_spec.ClearField(message.FieldReasoning, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetSessionID sets the "session_id" field.
func (_u *MessageUpdateOne) SetSessionID(v int64) *MessageUpdateOne {
	_u.mutation.ResetSessionID()
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableSessionID(v *int64) *MessageUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// AddSessionID adds value to the "session_id" field.
func (_u *MessageUpdateOne) AddSessionID(v int64) *MessageUpdateOne {
	_u.mutation.AddSessionID(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdateOne) SetRole(v string) *MessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableRole(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdateOne) SetContent(v string) *MessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableContent(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetReasoning sets the "reasoning" field.
func (_u *MessageUpdateOne) SetReasoning(v string) *MessageUpdateOne {
	_u.mutation.SetReasoning(v)
	return _u
}

// SetNillableReasoning sets the "reasoning" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableReasoning(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetReasoning(*v)
	}
	return _u
}

// ClearReasoning clears the value of the "reasoning" field.
func (_u *MessageUpdateOne) ClearReasoning() *MessageUpdateOne {
	_u.mutation.ClearReasoning()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MessageUpdateOne) SetCreatedAt(v time.Time) *MessageUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableCreatedAt(v *time.Time) *MessageUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(message.FieldSessionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSessionID(); ok {
		_spec.AddField(message.FieldSessionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reasoning(); ok {
		_spec.SetField(message.FieldReasoning, field.TypeString, value)
	}
	if _u.mutation.ReasoningCleared() {
		_spec.ClearField(message.FieldReasoning, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
