// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lifeink-ai/backend/ent/movie"
)

// Movie is the model entity for the Movie schema.
type Movie struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Cover holds the value of the "cover" field.
	Cover *string `json:"cover,omitempty"`
	// ReleaseDate holds the value of the "release_date" field.
	ReleaseDate *string `json:"release_date,omitempty"`
	// Rating holds the value of the "rating" field.
	Rating *int `json:"rating,omitempty"`
	// WatchDate holds the value of the "watch_date" field.
	WatchDate *string `json:"watch_date,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags *string `json:"tags,omitempty"`
	// Comment holds the value of the "comment" field.
	Comment *string `json:"comment,omitempty"`
	// ScrapedAt holds the value of the "scraped_at" field.
	ScrapedAt    time.Time `json:"scraped_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Movie) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case movie.FieldID, movie.FieldUserID, movie.FieldRating:
			values[i] = new(sql.NullInt64)
		case movie.FieldTitle, movie.FieldURL, movie.FieldCover, movie.FieldReleaseDate, movie.FieldWatchDate, movie.FieldTags, movie.FieldComment:
			values[i] = new(sql.NullString)
		case movie.FieldScrapedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Movie fields.
func (_m *Movie) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case movie.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case movie.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case movie.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case movie.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case movie.FieldCover:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover", values[i])
			} else if value.Valid {
				_m.Cover = new(string)
				*_m.Cover = value.String
			}
		case movie.FieldReleaseDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field release_date", values[i])
			} else if value.Valid {
				_m.ReleaseDate = new(string)
				*_m.ReleaseDate = value.String
			}
		case movie.FieldRating:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = new(int)
				*_m.Rating = int(value.Int64)
			}
		case movie.FieldWatchDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field watch_date", values[i])
			} else if value.Valid {
				_m.WatchDate = new(string)
				*_m.WatchDate = value.String
			}
		case movie.FieldTags:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value.Valid {
				_m.Tags = new(string)
				*_m.Tags = value.String
			}
		case movie.FieldComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comment", values[i])
			} else if value.Valid {
				_m.Comment = new(string)
				*_m.Comment = value.String
			}
		case movie.FieldScrapedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scraped_at", values[i])
			} else if value.Valid {
				_m.ScrapedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Movie.
// This includes values selected through modifiers, order, etc.
func (_m *Movie) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Movie.
// Note that you need to call Movie.Unwrap() before calling this method if this Movie
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Movie) Update() *MovieUpdateOne {
	return NewMovieClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Movie entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Movie) Unwrap() *Movie {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Movie is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Movie) String() string {
	var builder strings.Builder
	builder.WriteString("Movie(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	if v := _m.Cover; v != nil {
		builder.WriteString("cover=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReleaseDate; v != nil {
		builder.WriteString("release_date=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Rating; v != nil {
		builder.WriteString("rating=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.WatchDate; v != nil {
		builder.WriteString("watch_date=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Tags; v != nil {
		builder.WriteString("tags=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Comment; v != nil {
		builder.WriteString("comment=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("scraped_at=")
	builder.WriteString(_m.ScrapedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Movies is a parsable slice of Movie.
type Movies []*Movie
