// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lifeink-ai/backend/ent/movie"
)

// MovieCreate is the builder for creating a Movie entity.
type MovieCreate struct {
	config
	mutation *MovieMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *MovieCreate) SetUserID(v int64) *MovieCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *MovieCreate) SetTitle(v string) *MovieCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *MovieCreate) SetURL(v string) *MovieCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetCover sets the "cover" field.
func (_c *MovieCreate) SetCover(v string) *MovieCreate {
	_c.mutation.SetCover(v)
	return _c
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_c *MovieCreate) SetNillableCover(v *string) *MovieCreate {
	if v != nil {
		_c.SetCover(*v)
	}
	return _c
}

// SetReleaseDate sets the "release_date" field.
func (_c *MovieCreate) SetReleaseDate(v string) *MovieCreate {
	_c.mutation.SetReleaseDate(v)
	return _c
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_c *MovieCreate) SetNillableReleaseDate(v *string) *MovieCreate {
	if v != nil {
		_c.SetReleaseDate(*v)
	}
	return _c
}

// SetRating sets the "rating" field.
func (_c *MovieCreate) SetRating(v int) *MovieCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_c *MovieCreate) SetNillableRating(v *int) *MovieCreate {
	if v != nil {
		_c.SetRating(*v)
	}
	return _c
}

// SetWatchDate sets the "watch_date" field.
func (_c *MovieCreate) SetWatchDate(v string) *MovieCreate {
	_c.mutation.SetWatchDate(v)
	return _c
}

// SetNillableWatchDate sets the "watch_date" field if the given value is not nil.
func (_c *MovieCreate) SetNillableWatchDate(v *string) *MovieCreate {
	if v != nil {
		_c.SetWatchDate(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *MovieCreate) SetTags(v string) *MovieCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_c *MovieCreate) SetNillableTags(v *string) *MovieCreate {
	if v != nil {
		_c.SetTags(*v)
	}
	return _c
}

// SetComment sets the "comment" field.
func (_c *MovieCreate) SetComment(v string) *MovieCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *MovieCreate) SetNillableComment(v *string) *MovieCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetScrapedAt sets the "scraped_at" field.
func (_c *MovieCreate) SetScrapedAt(v time.Time) *MovieCreate {
	_c.mutation.SetScrapedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MovieCreate) SetID(v int64) *MovieCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MovieMutation object of the builder.
func (_c *MovieCreate) Mutation() *MovieMutation {
	return _c.mutation
}

// Save creates the Movie in the database.
func (_c *MovieCreate) Save(ctx context.Context) (*Movie, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MovieCreate) SaveX(ctx context.Context) *Movie {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MovieCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MovieCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MovieCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Movie.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Movie.title"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Movie.url"`)}
	}
	if _, ok := _c.mutation.ScrapedAt(); !ok {
		return &ValidationError{Name: "scraped_at", err: errors.New(`ent: missing required field "Movie.scraped_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := movie.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Movie.id": %w`, err)}
		}
	}
	return nil
}

func (_c *MovieCreate) sqlSave(ctx context.Context) (*Movie, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MovieCreate) createSpec() (*Movie, *sqlgraph.CreateSpec) {
	var (
		_node = &Movie{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(movie.Table, sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(movie.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(movie.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(movie.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Cover(); ok {
		_spec.SetField(movie.FieldCover, field.TypeString, value)
		_node.Cover = &value
	}
	if value, ok := _c.mutation.ReleaseDate(); ok {
		_spec.SetField(movie.FieldReleaseDate, field.TypeString, value)
		_node.ReleaseDate = &value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(movie.FieldRating, field.TypeInt, value)
		_node.Rating = &value
	}
	if value, ok := _c.mutation.WatchDate(); ok {
		_spec.SetField(movie.FieldWatchDate, field.TypeString, value)
		_node.WatchDate = &value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(movie.FieldTags, field.TypeString, value)
		_node.Tags = &value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(movie.FieldComment, field.TypeString, value)
		_node.Comment = &value
	}
	if value, ok := _c.mutation.ScrapedAt(); ok {
		_spec.SetField(movie.FieldScrapedAt, field.TypeTime, value)
		_node.ScrapedAt = value
	}
	return _node, _spec
}

// MovieCreateBulk is the builder for creating many Movie entities in bulk.
type MovieCreateBulk struct {
	config
	err      error
	builders []*MovieCreate
}

// Save creates the Movie entities in the database.
func (_c *MovieCreateBulk) Save(ctx context.Context) ([]*Movie, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Movie, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MovieMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MovieCreateBulk) SaveX(ctx context.Context) []*Movie {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MovieCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MovieCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
