// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lifeink-ai/backend/ent/note"
	"github.com/lifeink-ai/backend/ent/predicate"
)

// NoteUpdate is the builder for updating Note entities.
type NoteUpdate struct {
	config
	hooks    []Hook
	mutation *NoteMutation
}

// Where appends a list predicates to the NoteUpdate builder.
func (_u *NoteUpdate) Where(ps ...predicate.Note) *NoteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NoteUpdate) SetUserID(v int64) *NoteUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableUserID(v *int64) *NoteUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *NoteUpdate) AddUserID(v int64) *NoteUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *NoteUpdate) SetTitle(v string) *NoteUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableTitle(v *string) *NoteUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *NoteUpdate) SetURL(v string) *NoteUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableURL(v *string) *NoteUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *NoteUpdate) ClearURL() *NoteUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetDate sets the "date" field.
func (_u *NoteUpdate) SetDate(v string) *NoteUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableDate(v *string) *NoteUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// ClearDate clears the value of the "date" field.
func (_u *NoteUpdate) ClearDate() *NoteUpdate {
	_u.mutation.ClearDate()
	return _u
}

// SetLocation sets the "location" field.
func (_u *NoteUpdate) SetLocation(v string) *NoteUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableLocation(v *string) *NoteUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *NoteUpdate) ClearLocation() *NoteUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// SetBody sets the "body" field.
func (_u *NoteUpdate) SetBody(v string) *NoteUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableBody(v *string) *NoteUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *NoteUpdate) ClearBody() *NoteUpdate {
	_u.mutation.ClearBody()
	return _u
}

// SetScrapedAt sets the "scraped_at" field.
func (_u *NoteUpdate) SetScrapedAt(v time.Time) *NoteUpdate {
	_u.mutation.SetScrapedAt(v)
	return _u
}

// SetNillableScrapedAt sets the "scraped_at" field if the given value is not nil.
func (_u *NoteUpdate) SetNillableScrapedAt(v *time.Time) *NoteUpdate {
	if v != nil {
		_u.SetScrapedAt(*v)
	}
	return _u
}

// Mutation returns the NoteMutation object of the builder.
func (_u *NoteUpdate) Mutation() *NoteMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NoteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NoteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NoteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(note.Table, note.Columns, sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(note.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(note.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(note.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(note.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(note.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(note.FieldDate, field.TypeString, value)
	}
	if _u.mutation.DateCleared() {
		_spec.ClearField(note.FieldDate, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(note.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(note.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(note.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(note.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.ScrapedAt(); ok {
		_spec.SetField(note.FieldScrapedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{note.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NoteUpdateOne is the builder for updating a single Note entity.
type NoteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NoteMutation
}

// SetUserID sets the "user_id" field.
func (_u *NoteUpdateOne) SetUserID(v int64) *NoteUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableUserID(v *int64) *NoteUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *NoteUpdateOne) AddUserID(v int64) *NoteUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *NoteUpdateOne) SetTitle(v string) *NoteUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableTitle(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *NoteUpdateOne) SetURL(v string) *NoteUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableURL(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *NoteUpdateOne) ClearURL() *NoteUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetDate sets the "date" field.
func (_u *NoteUpdateOne) SetDate(v string) *NoteUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableDate(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// ClearDate clears the value of the "date" field.
func (_u *NoteUpdateOne) ClearDate() *NoteUpdateOne {
	_u.mutation.ClearDate()
	return _u
}

// SetLocation sets the "location" field.
func (_u *NoteUpdateOne) SetLocation(v string) *NoteUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableLocation(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *NoteUpdateOne) ClearLocation() *NoteUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// SetBody sets the "body" field.
func (_u *NoteUpdateOne) SetBody(v string) *NoteUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableBody(v *string) *NoteUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *NoteUpdateOne) ClearBody() *NoteUpdateOne {
	_u.mutation.ClearBody()
	return _u
}

// SetScrapedAt sets the "scraped_at" field.
func (_u *NoteUpdateOne) SetScrapedAt(v time.Time) *NoteUpdateOne {
	_u.mutation.SetScrapedAt(v)
	return _u
}

// SetNillableScrapedAt sets the "scraped_at" field if the given value is not nil.
func (_u *NoteUpdateOne) SetNillableScrapedAt(v *time.Time) *NoteUpdateOne {
	if v != nil {
		_u.SetScrapedAt(*v)
	}
	return _u
}

// Mutation returns the NoteMutation object of the builder.
func (_u *NoteUpdateOne) Mutation() *NoteMutation {
	return _u.mutation
}

// Where appends a list predicates to the NoteUpdate builder.
func (_u *NoteUpdateOne) Where(ps ...predicate.Note) *NoteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NoteUpdateOne) Select(field string, fields ...string) *NoteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Note entity.
func (_u *NoteUpdateOne) Save(ctx context.Context) (*Note, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoteUpdateOne) SaveX(ctx context.Context) *Note {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NoteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NoteUpdateOne) sqlSave(ctx context.Context) (_node *Note, err error) {
	_spec := sqlgraph.NewUpdateSpec(note.Table, note.Columns, sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Note.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, note.FieldID)
		for _, f := range fields {
			if !note.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != note.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(note.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(note.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(note.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(note.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(note.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(note.FieldDate, field.TypeString, value)
	}
	if _u.mutation.DateCleared() {
		_spec.ClearField(note.FieldDate, field.TypeString)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(note.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(note.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(note.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(note.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.ScrapedAt(); ok {
		_spec.SetField(note.FieldScrapedAt, field.TypeTime, value)
	}
	_node = &Note{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{note.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
