// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lifeink-ai/backend/ent/predicate"
	"github.com/lifeink-ai/backend/ent/review"
)

// ReviewUpdate is the builder for updating Review entities.
type ReviewUpdate struct {
	config
	hooks    []Hook
	mutation *ReviewMutation
}

// Where appends a list predicates to the ReviewUpdate builder.
func (_u *ReviewUpdate) Where(ps ...predicate.Review) *ReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ReviewUpdate) SetUserID(v int64) *ReviewUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableUserID(v *int64) *ReviewUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ReviewUpdate) AddUserID(v int64) *ReviewUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetSubjectTitle sets the "subject_title" field.
func (_u *ReviewUpdate) SetSubjectTitle(v string) *ReviewUpdate {
	_u.mutation.SetSubjectTitle(v)
	return _u
}

// SetNillableSubjectTitle sets the "subject_title" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableSubjectTitle(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetSubjectTitle(*v)
	}
	return _u
}

// SetSubjectURL sets the "subject_url" field.
func (_u *ReviewUpdate) SetSubjectURL(v string) *ReviewUpdate {
	_u.mutation.SetSubjectURL(v)
	return _u
}

// SetNillableSubjectURL sets the "subject_url" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableSubjectURL(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetSubjectURL(*v)
	}
	return _u
}

// ClearSubjectURL clears the value of the "subject_url" field.
func (_u *ReviewUpdate) ClearSubjectURL() *ReviewUpdate {
	_u.mutation.ClearSubjectURL()
	return _u
}

// SetSubjectImgURL sets the "subject_img_url" field.
func (_u *ReviewUpdate) SetSubjectImgURL(v string) *ReviewUpdate {
	_u.mutation.SetSubjectImgURL(v)
	return _u
}

// SetNillableSubjectImgURL sets the "subject_img_url" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableSubjectImgURL(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetSubjectImgURL(*v)
	}
	return _u
}

// ClearSubjectImgURL clears the value of the "subject_img_url" field.
func (_u *ReviewUpdate) ClearSubjectImgURL() *ReviewUpdate {
	_u.mutation.ClearSubjectImgURL()
	return _u
}

// SetReviewTitle sets the "review_title" field.
func (_u *ReviewUpdate) SetReviewTitle(v string) *ReviewUpdate {
	_u.mutation.SetReviewTitle(v)
	return _u
}

// SetNillableReviewTitle sets the "review_title" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableReviewTitle(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetReviewTitle(*v)
	}
	return _u
}

// ClearReviewTitle clears the value of the "review_title" field.
func (_u *ReviewUpdate) ClearReviewTitle() *ReviewUpdate {
	_u.mutation.ClearReviewTitle()
	return _u
}

// SetReviewURL sets the "review_url" field.
func (_u *ReviewUpdate) SetReviewURL(v string) *ReviewUpdate {
	_u.mutation.SetReviewURL(v)
	return _u
}

// SetNillableReviewURL sets the "review_url" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableReviewURL(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetReviewURL(*v)
	}
	return _u
}

// ClearReviewURL clears the value of the "review_url" field.
func (_u *ReviewUpdate) ClearReviewURL() *ReviewUpdate {
	_u.mutation.ClearReviewURL()
	return _u
}

// SetDate sets the "date" field.
func (_u *ReviewUpdate) SetDate(v string) *ReviewUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableDate(v *string) *ReviewUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// ClearDate clears the value of the "date" field.
func (_u *ReviewUpdate) ClearDate() *ReviewUpdate {
	_u.mutation.ClearDate()
	return _u
}

// SetScrapedAt sets the "scraped_at" field.
func (_u *ReviewUpdate) SetScrapedAt(v time.Time) *ReviewUpdate {
	_u.mutation.SetScrapedAt(v)
	return _u
}

// SetNillableScrapedAt sets the "scraped_at" field if the given value is not nil.
func (_u *ReviewUpdate) SetNillableScrapedAt(v *time.Time) *ReviewUpdate {
	if v != nil {
		_u.SetScrapedAt(*v)
	}
	return _u
}

// Mutation returns the ReviewMutation object of the builder.
func (_u *ReviewUpdate) Mutation() *ReviewMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReviewUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(review.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(review.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubjectTitle(); ok {
		_spec.SetField(review.FieldSubjectTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectURL(); ok {
		_spec.SetField(review.FieldSubjectURL, field.TypeString, value)
	}
	if _u.mutation.SubjectURLCleared() {
		_spec.ClearField(review.FieldSubjectURL, field.TypeString)
	}
	if value, ok := _u.mutation.SubjectImgURL(); ok {
		_spec.SetField(review.FieldSubjectImgURL, field.TypeString, value)
	}
	if _u.mutation.SubjectImgURLCleared() {
		_spec.ClearField(review.FieldSubjectImgURL, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewTitle(); ok {
		_spec.SetField(review.FieldReviewTitle, field.TypeString, value)
	}
	if _u.mutation.ReviewTitleCleared() {
		_spec.ClearField(review.FieldReviewTitle, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewURL(); ok {
		_spec.SetField(review.FieldReviewURL, field.TypeString, value)
	}
	if _u.mutation.ReviewURLCleared() {
		_spec.ClearField(review.FieldReviewURL, field.TypeString)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(review.FieldDate, field.TypeString, value)
	}
	if _u.mutation.DateCleared() {
		_spec.ClearField(review.FieldDate, field.TypeString)
	}
	if value, ok := _u.mutation.ScrapedAt(); ok {
		_spec.SetField(review.FieldScrapedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReviewUpdateOne is the builder for updating a single Review entity.
type ReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReviewMutation
}

// SetUserID sets the "user_id" field.
func (_u *ReviewUpdateOne) SetUserID(v int64) *ReviewUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableUserID(v *int64) *ReviewUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ReviewUpdateOne) AddUserID(v int64) *ReviewUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetSubjectTitle sets the "subject_title" field.
func (_u *ReviewUpdateOne) SetSubjectTitle(v string) *ReviewUpdateOne {
	_u.mutation.SetSubjectTitle(v)
	return _u
}

// SetNillableSubjectTitle sets the "subject_title" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableSubjectTitle(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetSubjectTitle(*v)
	}
	return _u
}

// SetSubjectURL sets the "subject_url" field.
func (_u *ReviewUpdateOne) SetSubjectURL(v string) *ReviewUpdateOne {
	_u.mutation.SetSubjectURL(v)
	return _u
}

// SetNillableSubjectURL sets the "subject_url" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableSubjectURL(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetSubjectURL(*v)
	}
	return _u
}

// ClearSubjectURL clears the value of the "subject_url" field.
func (_u *ReviewUpdateOne) ClearSubjectURL() *ReviewUpdateOne {
	_u.mutation.ClearSubjectURL()
	return _u
}

// SetSubjectImgURL sets the "subject_img_url" field.
func (_u *ReviewUpdateOne) SetSubjectImgURL(v string) *ReviewUpdateOne {
	_u.mutation.SetSubjectImgURL(v)
	return _u
}

// SetNillableSubjectImgURL sets the "subject_img_url" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableSubjectImgURL(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetSubjectImgURL(*v)
	}
	return _u
}

// ClearSubjectImgURL clears the value of the "subject_img_url" field.
func (_u *ReviewUpdateOne) ClearSubjectImgURL() *ReviewUpdateOne {
	_u.mutation.ClearSubjectImgURL()
	return _u
}

// SetReviewTitle sets the "review_title" field.
func (_u *ReviewUpdateOne) SetReviewTitle(v string) *ReviewUpdateOne {
	_u.mutation.SetReviewTitle(v)
	return _u
}

// SetNillableReviewTitle sets the "review_title" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableReviewTitle(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetReviewTitle(*v)
	}
	return _u
}

// ClearReviewTitle clears the value of the "review_title" field.
func (_u *ReviewUpdateOne) ClearReviewTitle() *ReviewUpdateOne {
	_u.mutation.ClearReviewTitle()
	return _u
}

// SetReviewURL sets the "review_url" field.
func (_u *ReviewUpdateOne) SetReviewURL(v string) *ReviewUpdateOne {
	_u.mutation.SetReviewURL(v)
	return _u
}

// SetNillableReviewURL sets the "review_url" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableReviewURL(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetReviewURL(*v)
	}
	return _u
}

// ClearReviewURL clears the value of the "review_url" field.
func (_u *ReviewUpdateOne) ClearReviewURL() *ReviewUpdateOne {
	_u.mutation.ClearReviewURL()
	return _u
}

// SetDate sets the "date" field.
func (_u *ReviewUpdateOne) SetDate(v string) *ReviewUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableDate(v *string) *ReviewUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// ClearDate clears the value of the "date" field.
func (_u *ReviewUpdateOne) ClearDate() *ReviewUpdateOne {
	_u.mutation.ClearDate()
	return _u
}

// SetScrapedAt sets the "scraped_at" field.
func (_u *ReviewUpdateOne) SetScrapedAt(v time.Time) *ReviewUpdateOne {
	_u.mutation.SetScrapedAt(v)
	return _u
}

// SetNillableScrapedAt sets the "scraped_at" field if the given value is not nil.
func (_u *ReviewUpdateOne) SetNillableScrapedAt(v *time.Time) *ReviewUpdateOne {
	if v != nil {
		_u.SetScrapedAt(*v)
	}
	return _u
}

// Mutation returns the ReviewMutation object of the builder.
func (_u *ReviewUpdateOne) Mutation() *ReviewMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReviewUpdate builder.
func (_u *ReviewUpdateOne) Where(ps ...predicate.Review) *ReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReviewUpdateOne) Select(field string, fields ...string) *ReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Review entity.
func (_u *ReviewUpdateOne) Save(ctx context.Context) (*Review, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReviewUpdateOne) SaveX(ctx context.Context) *Review {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ReviewUpdateOne) sqlSave(ctx context.Context) (_node *Review, err error) {
	_spec := sqlgraph.NewUpdateSpec(review.Table, review.Columns, sqlgraph.NewFieldSpec(review.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Review.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, review.FieldID)
		for _, f := range fields {
			if !review.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != review.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(review.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(review.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubjectTitle(); ok {
		_spec.SetField(review.FieldSubjectTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubjectURL(); ok {
		_spec.SetField(review.FieldSubjectURL, field.TypeString, value)
	}
	if _u.mutation.SubjectURLCleared() {
		_spec.ClearField(review.FieldSubjectURL, field.TypeString)
	}
	if value, ok := _u.mutation.SubjectImgURL(); ok {
		_spec.SetField(review.FieldSubjectImgURL, field.TypeString, value)
	}
	if _u.mutation.SubjectImgURLCleared() {
		_spec.ClearField(review.FieldSubjectImgURL, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewTitle(); ok {
		_spec.SetField(review.FieldReviewTitle, field.TypeString, value)
	}
	if _u.mutation.ReviewTitleCleared() {
		_spec.ClearField(review.FieldReviewTitle, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewURL(); ok {
		_spec.SetField(review.FieldReviewURL, field.TypeString, value)
	}
	if _u.mutation.ReviewURLCleared() {
		_spec.ClearField(review.FieldReviewURL, field.TypeString)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(review.FieldDate, field.TypeString, value)
	}
	if _u.mutation.DateCleared() {
		_spec.ClearField(review.FieldDate, field.TypeString)
	}
	if value, ok := _u.mutation.ScrapedAt(); ok {
		_spec.SetField(review.FieldScrapedAt, field.TypeTime, value)
	}
	_node = &Review{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{review.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
