// Code generated by ent, DO NOT EDIT.

package bookmark

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lifeink-ai/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldUserID, v))
}

// PlatformID applies equality check predicate on the "platform_id" field. It's identical to PlatformIDEQ.
func PlatformID(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldPlatformID, v))
}

// BookID applies equality check predicate on the "book_id" field. It's identical to BookIDEQ.
func BookID(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldBookID, v))
}

// BookTitle applies equality check predicate on the "book_title" field. It's identical to BookTitleEQ.
func BookTitle(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldBookTitle, v))
}

// MarkText applies equality check predicate on the "mark_text" field. It's identical to MarkTextEQ.
func MarkText(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldMarkText, v))
}

// ChapterName applies equality check predicate on the "chapter_name" field. It's identical to ChapterNameEQ.
func ChapterName(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldChapterName, v))
}

// ChapterIdx applies equality check predicate on the "chapter_idx" field. It's identical to ChapterIdxEQ.
func ChapterIdx(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldChapterIdx, v))
}

// Style applies equality check predicate on the "style" field. It's identical to StyleEQ.
func Style(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldStyle, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldCreateTime, v))
}

// BookmarkID applies equality check predicate on the "bookmark_id" field. It's identical to BookmarkIDEQ.
func BookmarkID(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldBookmarkID, v))
}

// ScrapedAt applies equality check predicate on the "scraped_at" field. It's identical to ScrapedAtEQ.
func ScrapedAt(v time.Time) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldScrapedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldUserID, v))
}

// PlatformIDEQ applies the EQ predicate on the "platform_id" field.
func PlatformIDEQ(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldPlatformID, v))
}

// PlatformIDNEQ applies the NEQ predicate on the "platform_id" field.
func PlatformIDNEQ(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldPlatformID, v))
}

// PlatformIDIn applies the In predicate on the "platform_id" field.
func PlatformIDIn(vs ...int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldPlatformID, vs...))
}

// PlatformIDNotIn applies the NotIn predicate on the "platform_id" field.
func PlatformIDNotIn(vs ...int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldPlatformID, vs...))
}

// PlatformIDGT applies the GT predicate on the "platform_id" field.
func PlatformIDGT(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldPlatformID, v))
}

// PlatformIDGTE applies the GTE predicate on the "platform_id" field.
func PlatformIDGTE(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldPlatformID, v))
}

// PlatformIDLT applies the LT predicate on the "platform_id" field.
func PlatformIDLT(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldPlatformID, v))
}

// PlatformIDLTE applies the LTE predicate on the "platform_id" field.
func PlatformIDLTE(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldPlatformID, v))
}

// BookIDEQ applies the EQ predicate on the "book_id" field.
func BookIDEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldBookID, v))
}

// BookIDNEQ applies the NEQ predicate on the "book_id" field.
func BookIDNEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldBookID, v))
}

// BookIDIn applies the In predicate on the "book_id" field.
func BookIDIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldBookID, vs...))
}

// BookIDNotIn applies the NotIn predicate on the "book_id" field.
func BookIDNotIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldBookID, vs...))
}

// BookIDGT applies the GT predicate on the "book_id" field.
func BookIDGT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldBookID, v))
}

// BookIDGTE applies the GTE predicate on the "book_id" field.
func BookIDGTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldBookID, v))
}

// BookIDLT applies the LT predicate on the "book_id" field.
func BookIDLT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldBookID, v))
}

// BookIDLTE applies the LTE predicate on the "book_id" field.
func BookIDLTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldBookID, v))
}

// BookIDContains applies the Contains predicate on the "book_id" field.
func BookIDContains(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContains(FieldBookID, v))
}

// BookIDHasPrefix applies the HasPrefix predicate on the "book_id" field.
func BookIDHasPrefix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasPrefix(FieldBookID, v))
}

// BookIDHasSuffix applies the HasSuffix predicate on the "book_id" field.
func BookIDHasSuffix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasSuffix(FieldBookID, v))
}

// BookIDEqualFold applies the EqualFold predicate on the "book_id" field.
func BookIDEqualFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEqualFold(FieldBookID, v))
}

// BookIDContainsFold applies the ContainsFold predicate on the "book_id" field.
func BookIDContainsFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContainsFold(FieldBookID, v))
}

// BookTitleEQ applies the EQ predicate on the "book_title" field.
func BookTitleEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldBookTitle, v))
}

// BookTitleNEQ applies the NEQ predicate on the "book_title" field.
func BookTitleNEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldBookTitle, v))
}

// BookTitleIn applies the In predicate on the "book_title" field.
func BookTitleIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldBookTitle, vs...))
}

// BookTitleNotIn applies the NotIn predicate on the "book_title" field.
func BookTitleNotIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldBookTitle, vs...))
}

// BookTitleGT applies the GT predicate on the "book_title" field.
func BookTitleGT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldBookTitle, v))
}

// BookTitleGTE applies the GTE predicate on the "book_title" field.
func BookTitleGTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldBookTitle, v))
}

// BookTitleLT applies the LT predicate on the "book_title" field.
func BookTitleLT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldBookTitle, v))
}

// BookTitleLTE applies the LTE predicate on the "book_title" field.
func BookTitleLTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldBookTitle, v))
}

// BookTitleContains applies the Contains predicate on the "book_title" field.
func BookTitleContains(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContains(FieldBookTitle, v))
}

// BookTitleHasPrefix applies the HasPrefix predicate on the "book_title" field.
func BookTitleHasPrefix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasPrefix(FieldBookTitle, v))
}

// BookTitleHasSuffix applies the HasSuffix predicate on the "book_title" field.
func BookTitleHasSuffix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasSuffix(FieldBookTitle, v))
}

// BookTitleIsNil applies the IsNil predicate on the "book_title" field.
func BookTitleIsNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIsNull(FieldBookTitle))
}

// BookTitleNotNil applies the NotNil predicate on the "book_title" field.
func BookTitleNotNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotNull(FieldBookTitle))
}

// BookTitleEqualFold applies the EqualFold predicate on the "book_title" field.
func BookTitleEqualFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEqualFold(FieldBookTitle, v))
}

// BookTitleContainsFold applies the ContainsFold predicate on the "book_title" field.
func BookTitleContainsFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContainsFold(FieldBookTitle, v))
}

// MarkTextEQ applies the EQ predicate on the "mark_text" field.
func MarkTextEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldMarkText, v))
}

// MarkTextNEQ applies the NEQ predicate on the "mark_text" field.
func MarkTextNEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldMarkText, v))
}

// MarkTextIn applies the In predicate on the "mark_text" field.
func MarkTextIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldMarkText, vs...))
}

// MarkTextNotIn applies the NotIn predicate on the "mark_text" field.
func MarkTextNotIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldMarkText, vs...))
}

// MarkTextGT applies the GT predicate on the "mark_text" field.
func MarkTextGT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldMarkText, v))
}

// MarkTextGTE applies the GTE predicate on the "mark_text" field.
func MarkTextGTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldMarkText, v))
}

// MarkTextLT applies the LT predicate on the "mark_text" field.
func MarkTextLT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldMarkText, v))
}

// MarkTextLTE applies the LTE predicate on the "mark_text" field.
func MarkTextLTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldMarkText, v))
}

// MarkTextContains applies the Contains predicate on the "mark_text" field.
func MarkTextContains(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContains(FieldMarkText, v))
}

// MarkTextHasPrefix applies the HasPrefix predicate on the "mark_text" field.
func MarkTextHasPrefix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasPrefix(FieldMarkText, v))
}

// MarkTextHasSuffix applies the HasSuffix predicate on the "mark_text" field.
func MarkTextHasSuffix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasSuffix(FieldMarkText, v))
}

// MarkTextEqualFold applies the EqualFold predicate on the "mark_text" field.
func MarkTextEqualFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEqualFold(FieldMarkText, v))
}

// MarkTextContainsFold applies the ContainsFold predicate on the "mark_text" field.
func MarkTextContainsFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContainsFold(FieldMarkText, v))
}

// ChapterNameEQ applies the EQ predicate on the "chapter_name" field.
func ChapterNameEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldChapterName, v))
}

// ChapterNameNEQ applies the NEQ predicate on the "chapter_name" field.
func ChapterNameNEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldChapterName, v))
}

// ChapterNameIn applies the In predicate on the "chapter_name" field.
func ChapterNameIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldChapterName, vs...))
}

// ChapterNameNotIn applies the NotIn predicate on the "chapter_name" field.
func ChapterNameNotIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldChapterName, vs...))
}

// ChapterNameGT applies the GT predicate on the "chapter_name" field.
func ChapterNameGT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldChapterName, v))
}

// ChapterNameGTE applies the GTE predicate on the "chapter_name" field.
func ChapterNameGTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldChapterName, v))
}

// ChapterNameLT applies the LT predicate on the "chapter_name" field.
func ChapterNameLT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldChapterName, v))
}

// ChapterNameLTE applies the LTE predicate on the "chapter_name" field.
func ChapterNameLTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldChapterName, v))
}

// ChapterNameContains applies the Contains predicate on the "chapter_name" field.
func ChapterNameContains(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContains(FieldChapterName, v))
}

// ChapterNameHasPrefix applies the HasPrefix predicate on the "chapter_name" field.
func ChapterNameHasPrefix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasPrefix(FieldChapterName, v))
}

// ChapterNameHasSuffix applies the HasSuffix predicate on the "chapter_name" field.
func ChapterNameHasSuffix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasSuffix(FieldChapterName, v))
}

// ChapterNameIsNil applies the IsNil predicate on the "chapter_name" field.
func ChapterNameIsNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIsNull(FieldChapterName))
}

// ChapterNameNotNil applies the NotNil predicate on the "chapter_name" field.
func ChapterNameNotNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotNull(FieldChapterName))
}

// ChapterNameEqualFold applies the EqualFold predicate on the "chapter_name" field.
func ChapterNameEqualFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEqualFold(FieldChapterName, v))
}

// ChapterNameContainsFold applies the ContainsFold predicate on the "chapter_name" field.
func ChapterNameContainsFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContainsFold(FieldChapterName, v))
}

// ChapterIdxEQ applies the EQ predicate on the "chapter_idx" field.
func ChapterIdxEQ(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldChapterIdx, v))
}

// ChapterIdxNEQ applies the NEQ predicate on the "chapter_idx" field.
func ChapterIdxNEQ(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldChapterIdx, v))
}

// ChapterIdxIn applies the In predicate on the "chapter_idx" field.
func ChapterIdxIn(vs ...int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldChapterIdx, vs...))
}

// ChapterIdxNotIn applies the NotIn predicate on the "chapter_idx" field.
func ChapterIdxNotIn(vs ...int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldChapterIdx, vs...))
}

// ChapterIdxGT applies the GT predicate on the "chapter_idx" field.
func ChapterIdxGT(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldChapterIdx, v))
}

// ChapterIdxGTE applies the GTE predicate on the "chapter_idx" field.
func ChapterIdxGTE(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldChapterIdx, v))
}

// ChapterIdxLT applies the LT predicate on the "chapter_idx" field.
func ChapterIdxLT(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldChapterIdx, v))
}

// ChapterIdxLTE applies the LTE predicate on the "chapter_idx" field.
func ChapterIdxLTE(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldChapterIdx, v))
}

// ChapterIdxIsNil applies the IsNil predicate on the "chapter_idx" field.
func ChapterIdxIsNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIsNull(FieldChapterIdx))
}

// ChapterIdxNotNil applies the NotNil predicate on the "chapter_idx" field.
func ChapterIdxNotNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotNull(FieldChapterIdx))
}

// StyleEQ applies the EQ predicate on the "style" field.
func StyleEQ(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldStyle, v))
}

// StyleNEQ applies the NEQ predicate on the "style" field.
func StyleNEQ(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldStyle, v))
}

// StyleIn applies the In predicate on the "style" field.
func StyleIn(vs ...int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldStyle, vs...))
}

// StyleNotIn applies the NotIn predicate on the "style" field.
func StyleNotIn(vs ...int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldStyle, vs...))
}

// StyleGT applies the GT predicate on the "style" field.
func StyleGT(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldStyle, v))
}

// StyleGTE applies the GTE predicate on the "style" field.
func StyleGTE(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldStyle, v))
}

// StyleLT applies the LT predicate on the "style" field.
func StyleLT(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldStyle, v))
}

// StyleLTE applies the LTE predicate on the "style" field.
func StyleLTE(v int) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldStyle, v))
}

// StyleIsNil applies the IsNil predicate on the "style" field.
func StyleIsNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIsNull(FieldStyle))
}

// StyleNotNil applies the NotNil predicate on the "style" field.
func StyleNotNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotNull(FieldStyle))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v int64) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotNull(FieldCreateTime))
}

// BookmarkIDEQ applies the EQ predicate on the "bookmark_id" field.
func BookmarkIDEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldBookmarkID, v))
}

// BookmarkIDNEQ applies the NEQ predicate on the "bookmark_id" field.
func BookmarkIDNEQ(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldBookmarkID, v))
}

// BookmarkIDIn applies the In predicate on the "bookmark_id" field.
func BookmarkIDIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldBookmarkID, vs...))
}

// BookmarkIDNotIn applies the NotIn predicate on the "bookmark_id" field.
func BookmarkIDNotIn(vs ...string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldBookmarkID, vs...))
}

// BookmarkIDGT applies the GT predicate on the "bookmark_id" field.
func BookmarkIDGT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldBookmarkID, v))
}

// BookmarkIDGTE applies the GTE predicate on the "bookmark_id" field.
func BookmarkIDGTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldBookmarkID, v))
}

// BookmarkIDLT applies the LT predicate on the "bookmark_id" field.
func BookmarkIDLT(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldBookmarkID, v))
}

// BookmarkIDLTE applies the LTE predicate on the "bookmark_id" field.
func BookmarkIDLTE(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldBookmarkID, v))
}

// BookmarkIDContains applies the Contains predicate on the "bookmark_id" field.
func BookmarkIDContains(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContains(FieldBookmarkID, v))
}

// BookmarkIDHasPrefix applies the HasPrefix predicate on the "bookmark_id" field.
func BookmarkIDHasPrefix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasPrefix(FieldBookmarkID, v))
}

// BookmarkIDHasSuffix applies the HasSuffix predicate on the "bookmark_id" field.
func BookmarkIDHasSuffix(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldHasSuffix(FieldBookmarkID, v))
}

// BookmarkIDIsNil applies the IsNil predicate on the "bookmark_id" field.
func BookmarkIDIsNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIsNull(FieldBookmarkID))
}

// BookmarkIDNotNil applies the NotNil predicate on the "bookmark_id" field.
func BookmarkIDNotNil() predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotNull(FieldBookmarkID))
}

// BookmarkIDEqualFold applies the EqualFold predicate on the "bookmark_id" field.
func BookmarkIDEqualFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEqualFold(FieldBookmarkID, v))
}

// BookmarkIDContainsFold applies the ContainsFold predicate on the "bookmark_id" field.
func BookmarkIDContainsFold(v string) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldContainsFold(FieldBookmarkID, v))
}

// ScrapedAtEQ applies the EQ predicate on the "scraped_at" field.
func ScrapedAtEQ(v time.Time) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldEQ(FieldScrapedAt, v))
}

// ScrapedAtNEQ applies the NEQ predicate on the "scraped_at" field.
func ScrapedAtNEQ(v time.Time) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNEQ(FieldScrapedAt, v))
}

// ScrapedAtIn applies the In predicate on the "scraped_at" field.
func ScrapedAtIn(vs ...time.Time) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldIn(FieldScrapedAt, vs...))
}

// ScrapedAtNotIn applies the NotIn predicate on the "scraped_at" field.
func ScrapedAtNotIn(vs ...time.Time) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldNotIn(FieldScrapedAt, vs...))
}

// ScrapedAtGT applies the GT predicate on the "scraped_at" field.
func ScrapedAtGT(v time.Time) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGT(FieldScrapedAt, v))
}

// ScrapedAtGTE applies the GTE predicate on the "scraped_at" field.
func ScrapedAtGTE(v time.Time) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldGTE(FieldScrapedAt, v))
}

// ScrapedAtLT applies the LT predicate on the "scraped_at" field.
func ScrapedAtLT(v time.Time) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLT(FieldScrapedAt, v))
}

// ScrapedAtLTE applies the LTE predicate on the "scraped_at" field.
func ScrapedAtLTE(v time.Time) predicate.Bookmark {
	return predicate.Bookmark(sql.FieldLTE(FieldScrapedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Bookmark) predicate.Bookmark {
	return predicate.Bookmark(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Bookmark) predicate.Bookmark {
	return predicate.Bookmark(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Bookmark) predicate.Bookmark {
	return predicate.Bookmark(sql.NotPredicates(p))
}
