// Code generated by ent, DO NOT EDIT.

package note

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the note type in the database.
	Label = "note"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPlatformID holds the string denoting the platform_id field in the database.
	FieldPlatformID = "platform_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldBookID holds the string denoting the book_id field in the database.
	FieldBookID = "book_id"
	// FieldAbstract holds the string denoting the abstract field in the database.
	FieldAbstract = "abstract"
	// FieldScrapedAt holds the string denoting the scraped_at field in the database.
	FieldScrapedAt = "scraped_at"
	// Table holds the table name of the note in the database.
	Table = "notes"
)

// Columns holds all SQL columns for note fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldPlatformID,
	FieldTitle,
	FieldURL,
	FieldDate,
	FieldLocation,
	FieldBody,
	FieldBookID,
	FieldAbstract,
	FieldScrapedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the Note queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPlatformID orders the results by the platform_id field.
func ByPlatformID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByBookID orders the results by the book_id field.
func ByBookID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBookID, opts...).ToFunc()
}

// ByAbstract orders the results by the abstract field.
func ByAbstract(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbstract, opts...).ToFunc()
}

// ByScrapedAt orders the results by the scraped_at field.
func ByScrapedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScrapedAt, opts...).ToFunc()
}
