// Code generated by ent, DO NOT EDIT.

package note

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lifeink-ai/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldUserID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldTitle, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldURL, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldDate, v))
}

// Location applies equality check predicate on the "location" field. It's identical to LocationEQ.
func Location(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldLocation, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldBody, v))
}

// BookID applies equality check predicate on the "book_id" field. It's identical to BookIDEQ.
func BookID(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldBookID, v))
}

// ChapterName applies equality check predicate on the "chapter_name" field. It's identical to ChapterNameEQ.
func ChapterName(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldChapterName, v))
}

// Abstract applies equality check predicate on the "abstract" field. It's identical to AbstractEQ.
func Abstract(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldAbstract, v))
}

// ReviewID applies equality check predicate on the "review_id" field. It's identical to ReviewIDEQ.
func ReviewID(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldReviewID, v))
}

// ScrapedAt applies equality check predicate on the "scraped_at" field. It's identical to ScrapedAtEQ.
func ScrapedAt(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldScrapedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldUserID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldTitle, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldURL, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldDate, v))
}

// DateContains applies the Contains predicate on the "date" field.
func DateContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldDate, v))
}

// DateHasPrefix applies the HasPrefix predicate on the "date" field.
func DateHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldDate, v))
}

// DateHasSuffix applies the HasSuffix predicate on the "date" field.
func DateHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldDate, v))
}

// DateIsNil applies the IsNil predicate on the "date" field.
func DateIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldDate))
}

// DateNotNil applies the NotNil predicate on the "date" field.
func DateNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldDate))
}

// DateEqualFold applies the EqualFold predicate on the "date" field.
func DateEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldDate, v))
}

// DateContainsFold applies the ContainsFold predicate on the "date" field.
func DateContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldDate, v))
}

// LocationEQ applies the EQ predicate on the "location" field.
func LocationEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldLocation, v))
}

// LocationNEQ applies the NEQ predicate on the "location" field.
func LocationNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldLocation, v))
}

// LocationIn applies the In predicate on the "location" field.
func LocationIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldLocation, vs...))
}

// LocationNotIn applies the NotIn predicate on the "location" field.
func LocationNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldLocation, vs...))
}

// LocationGT applies the GT predicate on the "location" field.
func LocationGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldLocation, v))
}

// LocationGTE applies the GTE predicate on the "location" field.
func LocationGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldLocation, v))
}

// LocationLT applies the LT predicate on the "location" field.
func LocationLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldLocation, v))
}

// LocationLTE applies the LTE predicate on the "location" field.
func LocationLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldLocation, v))
}

// LocationContains applies the Contains predicate on the "location" field.
func LocationContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldLocation, v))
}

// LocationHasPrefix applies the HasPrefix predicate on the "location" field.
func LocationHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldLocation, v))
}

// LocationHasSuffix applies the HasSuffix predicate on the "location" field.
func LocationHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldLocation, v))
}

// LocationIsNil applies the IsNil predicate on the "location" field.
func LocationIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldLocation))
}

// LocationNotNil applies the NotNil predicate on the "location" field.
func LocationNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldLocation))
}

// LocationEqualFold applies the EqualFold predicate on the "location" field.
func LocationEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldLocation, v))
}

// LocationContainsFold applies the ContainsFold predicate on the "location" field.
func LocationContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldLocation, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldBody, v))
}

// BodyIsNil applies the IsNil predicate on the "body" field.
func BodyIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldBody))
}

// BodyNotNil applies the NotNil predicate on the "body" field.
func BodyNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldBody))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldBody, v))
}

// BookIDEQ applies the EQ predicate on the "book_id" field.
func BookIDEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldBookID, v))
}

// BookIDNEQ applies the NEQ predicate on the "book_id" field.
func BookIDNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldBookID, v))
}

// BookIDIn applies the In predicate on the "book_id" field.
func BookIDIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldBookID, vs...))
}

// BookIDNotIn applies the NotIn predicate on the "book_id" field.
func BookIDNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldBookID, vs...))
}

// BookIDGT applies the GT predicate on the "book_id" field.
func BookIDGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldBookID, v))
}

// BookIDGTE applies the GTE predicate on the "book_id" field.
func BookIDGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldBookID, v))
}

// BookIDLT applies the LT predicate on the "book_id" field.
func BookIDLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldBookID, v))
}

// BookIDLTE applies the LTE predicate on the "book_id" field.
func BookIDLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldBookID, v))
}

// BookIDContains applies the Contains predicate on the "book_id" field.
func BookIDContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldBookID, v))
}

// BookIDHasPrefix applies the HasPrefix predicate on the "book_id" field.
func BookIDHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldBookID, v))
}

// BookIDHasSuffix applies the HasSuffix predicate on the "book_id" field.
func BookIDHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldBookID, v))
}

// BookIDIsNil applies the IsNil predicate on the "book_id" field.
func BookIDIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldBookID))
}

// BookIDNotNil applies the NotNil predicate on the "book_id" field.
func BookIDNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldBookID))
}

// BookIDEqualFold applies the EqualFold predicate on the "book_id" field.
func BookIDEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldBookID, v))
}

// BookIDContainsFold applies the ContainsFold predicate on the "book_id" field.
func BookIDContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldBookID, v))
}

// ChapterNameEQ applies the EQ predicate on the "chapter_name" field.
func ChapterNameEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldChapterName, v))
}

// ChapterNameNEQ applies the NEQ predicate on the "chapter_name" field.
func ChapterNameNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldChapterName, v))
}

// ChapterNameIn applies the In predicate on the "chapter_name" field.
func ChapterNameIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldChapterName, vs...))
}

// ChapterNameNotIn applies the NotIn predicate on the "chapter_name" field.
func ChapterNameNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldChapterName, vs...))
}

// ChapterNameGT applies the GT predicate on the "chapter_name" field.
func ChapterNameGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldChapterName, v))
}

// ChapterNameGTE applies the GTE predicate on the "chapter_name" field.
func ChapterNameGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldChapterName, v))
}

// ChapterNameLT applies the LT predicate on the "chapter_name" field.
func ChapterNameLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldChapterName, v))
}

// ChapterNameLTE applies the LTE predicate on the "chapter_name" field.
func ChapterNameLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldChapterName, v))
}

// ChapterNameContains applies the Contains predicate on the "chapter_name" field.
func ChapterNameContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldChapterName, v))
}

// ChapterNameHasPrefix applies the HasPrefix predicate on the "chapter_name" field.
func ChapterNameHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldChapterName, v))
}

// ChapterNameHasSuffix applies the HasSuffix predicate on the "chapter_name" field.
func ChapterNameHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldChapterName, v))
}

// ChapterNameIsNil applies the IsNil predicate on the "chapter_name" field.
func ChapterNameIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldChapterName))
}

// ChapterNameNotNil applies the NotNil predicate on the "chapter_name" field.
func ChapterNameNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldChapterName))
}

// ChapterNameEqualFold applies the EqualFold predicate on the "chapter_name" field.
func ChapterNameEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldChapterName, v))
}

// ChapterNameContainsFold applies the ContainsFold predicate on the "chapter_name" field.
func ChapterNameContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldChapterName, v))
}

// AbstractEQ applies the EQ predicate on the "abstract" field.
func AbstractEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldAbstract, v))
}

// AbstractNEQ applies the NEQ predicate on the "abstract" field.
func AbstractNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldAbstract, v))
}

// AbstractIn applies the In predicate on the "abstract" field.
func AbstractIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldAbstract, vs...))
}

// AbstractNotIn applies the NotIn predicate on the "abstract" field.
func AbstractNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldAbstract, vs...))
}

// AbstractGT applies the GT predicate on the "abstract" field.
func AbstractGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldAbstract, v))
}

// AbstractGTE applies the GTE predicate on the "abstract" field.
func AbstractGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldAbstract, v))
}

// AbstractLT applies the LT predicate on the "abstract" field.
func AbstractLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldAbstract, v))
}

// AbstractLTE applies the LTE predicate on the "abstract" field.
func AbstractLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldAbstract, v))
}

// AbstractContains applies the Contains predicate on the "abstract" field.
func AbstractContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldAbstract, v))
}

// AbstractHasPrefix applies the HasPrefix predicate on the "abstract" field.
func AbstractHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldAbstract, v))
}

// AbstractHasSuffix applies the HasSuffix predicate on the "abstract" field.
func AbstractHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldAbstract, v))
}

// AbstractIsNil applies the IsNil predicate on the "abstract" field.
func AbstractIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldAbstract))
}

// AbstractNotNil applies the NotNil predicate on the "abstract" field.
func AbstractNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldAbstract))
}

// AbstractEqualFold applies the EqualFold predicate on the "abstract" field.
func AbstractEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldAbstract, v))
}

// AbstractContainsFold applies the ContainsFold predicate on the "abstract" field.
func AbstractContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldAbstract, v))
}

// ReviewIDEQ applies the EQ predicate on the "review_id" field.
func ReviewIDEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldReviewID, v))
}

// ReviewIDNEQ applies the NEQ predicate on the "review_id" field.
func ReviewIDNEQ(v string) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldReviewID, v))
}

// ReviewIDIn applies the In predicate on the "review_id" field.
func ReviewIDIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldReviewID, vs...))
}

// ReviewIDNotIn applies the NotIn predicate on the "review_id" field.
func ReviewIDNotIn(vs ...string) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldReviewID, vs...))
}

// ReviewIDGT applies the GT predicate on the "review_id" field.
func ReviewIDGT(v string) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldReviewID, v))
}

// ReviewIDGTE applies the GTE predicate on the "review_id" field.
func ReviewIDGTE(v string) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldReviewID, v))
}

// ReviewIDLT applies the LT predicate on the "review_id" field.
func ReviewIDLT(v string) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldReviewID, v))
}

// ReviewIDLTE applies the LTE predicate on the "review_id" field.
func ReviewIDLTE(v string) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldReviewID, v))
}

// ReviewIDContains applies the Contains predicate on the "review_id" field.
func ReviewIDContains(v string) predicate.Note {
	return predicate.Note(sql.FieldContains(FieldReviewID, v))
}

// ReviewIDHasPrefix applies the HasPrefix predicate on the "review_id" field.
func ReviewIDHasPrefix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasPrefix(FieldReviewID, v))
}

// ReviewIDHasSuffix applies the HasSuffix predicate on the "review_id" field.
func ReviewIDHasSuffix(v string) predicate.Note {
	return predicate.Note(sql.FieldHasSuffix(FieldReviewID, v))
}

// ReviewIDIsNil applies the IsNil predicate on the "review_id" field.
func ReviewIDIsNil() predicate.Note {
	return predicate.Note(sql.FieldIsNull(FieldReviewID))
}

// ReviewIDNotNil applies the NotNil predicate on the "review_id" field.
func ReviewIDNotNil() predicate.Note {
	return predicate.Note(sql.FieldNotNull(FieldReviewID))
}

// ReviewIDEqualFold applies the EqualFold predicate on the "review_id" field.
func ReviewIDEqualFold(v string) predicate.Note {
	return predicate.Note(sql.FieldEqualFold(FieldReviewID, v))
}

// ReviewIDContainsFold applies the ContainsFold predicate on the "review_id" field.
func ReviewIDContainsFold(v string) predicate.Note {
	return predicate.Note(sql.FieldContainsFold(FieldReviewID, v))
}

// ScrapedAtEQ applies the EQ predicate on the "scraped_at" field.
func ScrapedAtEQ(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldEQ(FieldScrapedAt, v))
}

// ScrapedAtNEQ applies the NEQ predicate on the "scraped_at" field.
func ScrapedAtNEQ(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldNEQ(FieldScrapedAt, v))
}

// ScrapedAtIn applies the In predicate on the "scraped_at" field.
func ScrapedAtIn(vs ...time.Time) predicate.Note {
	return predicate.Note(sql.FieldIn(FieldScrapedAt, vs...))
}

// ScrapedAtNotIn applies the NotIn predicate on the "scraped_at" field.
func ScrapedAtNotIn(vs ...time.Time) predicate.Note {
	return predicate.Note(sql.FieldNotIn(FieldScrapedAt, vs...))
}

// ScrapedAtGT applies the GT predicate on the "scraped_at" field.
func ScrapedAtGT(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldGT(FieldScrapedAt, v))
}

// ScrapedAtGTE applies the GTE predicate on the "scraped_at" field.
func ScrapedAtGTE(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldGTE(FieldScrapedAt, v))
}

// ScrapedAtLT applies the LT predicate on the "scraped_at" field.
func ScrapedAtLT(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldLT(FieldScrapedAt, v))
}

// ScrapedAtLTE applies the LTE predicate on the "scraped_at" field.
func ScrapedAtLTE(v time.Time) predicate.Note {
	return predicate.Note(sql.FieldLTE(FieldScrapedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Note) predicate.Note {
	return predicate.Note(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Note) predicate.Note {
	return predicate.Note(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Note) predicate.Note {
	return predicate.Note(sql.NotPredicates(p))
}
