// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BooksColumns holds the columns for the "books" table.
	BooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "platform_id", Type: field.TypeInt},
		{Name: "title", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "cover", Type: field.TypeString, Nullable: true},
		{Name: "author", Type: field.TypeString, Nullable: true},
		{Name: "country", Type: field.TypeString, Nullable: true},
		{Name: "translator", Type: field.TypeString, Nullable: true},
		{Name: "publisher", Type: field.TypeString, Nullable: true},
		{Name: "pub_date", Type: field.TypeString, Nullable: true},
		{Name: "price", Type: field.TypeString, Nullable: true},
		{Name: "rating", Type: field.TypeInt, Nullable: true},
		{Name: "read_date", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Nullable: true},
		{Name: "tags", Type: field.TypeString, Nullable: true},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "external", Type: field.TypeString, Nullable: true},
		{Name: "scraped_at", Type: field.TypeTime},
	}
	// BooksTable holds the schema information for the "books" table.
	BooksTable = &schema.Table{
		Name:       "books",
		Columns:    BooksColumns,
		PrimaryKey: []*schema.Column{BooksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "book_user_id_url_platform_id",
				Unique:  true,
				Columns: []*schema.Column{BooksColumns[1], BooksColumns[4], BooksColumns[2]},
			},
		},
	}
	// BookmarksColumns holds the columns for the "bookmarks" table.
	BookmarksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "platform_id", Type: field.TypeInt},
		{Name: "book_id", Type: field.TypeString},
		{Name: "book_title", Type: field.TypeString, Nullable: true},
		{Name: "mark_text", Type: field.TypeString},
		{Name: "chapter_name", Type: field.TypeString, Nullable: true},
		{Name: "chapter_idx", Type: field.TypeInt, Nullable: true},
		{Name: "style", Type: field.TypeInt, Nullable: true},
		{Name: "create_time", Type: field.TypeInt64, Nullable: true},
		{Name: "bookmark_id", Type: field.TypeString, Nullable: true},
		{Name: "scraped_at", Type: field.TypeTime},
	}
	// BookmarksTable holds the schema information for the "bookmarks" table.
	BookmarksTable = &schema.Table{
		Name:       "bookmarks",
		Columns:    BookmarksColumns,
		PrimaryKey: []*schema.Column{BookmarksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "bookmark_user_id_platform_id_book_id_bookmark_id",
				Unique:  true,
				Columns: []*schema.Column{BookmarksColumns[1], BookmarksColumns[2], BookmarksColumns[3], BookmarksColumns[10]},
			},
		},
	}
	// CommunityMetaColumns holds the columns for the "community_meta" table.
	CommunityMetaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "platform_id", Type: field.TypeInt},
		{Name: "bound", Type: field.TypeInt, Default: 0},
		{Name: "community_user_id", Type: field.TypeString, Nullable: true},
		{Name: "profile_json", Type: field.TypeString, Nullable: true},
		{Name: "session_state_json", Type: field.TypeString, Nullable: true},
		{Name: "session_expires_at", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CommunityMetaTable holds the schema information for the "community_meta" table.
	CommunityMetaTable = &schema.Table{
		Name:       "community_meta",
		Columns:    CommunityMetaColumns,
		PrimaryKey: []*schema.Column{CommunityMetaColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "communitymeta_user_id_platform_id",
				Unique:  true,
				Columns: []*schema.Column{CommunityMetaColumns[1], CommunityMetaColumns[2]},
			},
		},
	}
	// FlomoMemosColumns holds the columns for the "flomo_memos" table.
	FlomoMemosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "platform_id", Type: field.TypeInt},
		{Name: "content", Type: field.TypeString},
		{Name: "tags", Type: field.TypeString, Nullable: true},
		{Name: "files", Type: field.TypeString, Nullable: true},
		{Name: "memo_created_at", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "scraped_at", Type: field.TypeTime},
	}
	// FlomoMemosTable holds the schema information for the "flomo_memos" table.
	FlomoMemosTable = &schema.Table{
		Name:       "flomo_memos",
		Columns:    FlomoMemosColumns,
		PrimaryKey: []*schema.Column{FlomoMemosColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "flomomemo_user_id_platform_id_memo_created_at",
				Unique:  true,
				Columns: []*schema.Column{FlomoMemosColumns[1], FlomoMemosColumns[2], FlomoMemosColumns[6]},
			},
		},
	}
	// GamesColumns holds the columns for the "games" table.
	GamesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "title", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "cover", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "rating", Type: field.TypeInt, Nullable: true},
		{Name: "release_date", Type: field.TypeString, Nullable: true},
		{Name: "play_date", Type: field.TypeString, Nullable: true},
		{Name: "tags", Type: field.TypeString, Nullable: true},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "scraped_at", Type: field.TypeTime},
	}
	// GamesTable holds the schema information for the "games" table.
	GamesTable = &schema.Table{
		Name:       "games",
		Columns:    GamesColumns,
		PrimaryKey: []*schema.Column{GamesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "game_user_id_url",
				Unique:  true,
				Columns: []*schema.Column{GamesColumns[1], GamesColumns[3]},
			},
		},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "session_id", Type: field.TypeInt64},
		{Name: "role", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "reasoning", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
	}
	// MoviesColumns holds the columns for the "movies" table.
	MoviesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "title", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "cover", Type: field.TypeString, Nullable: true},
		{Name: "release_date", Type: field.TypeString, Nullable: true},
		{Name: "rating", Type: field.TypeInt, Nullable: true},
		{Name: "watch_date", Type: field.TypeString, Nullable: true},
		{Name: "tags", Type: field.TypeString, Nullable: true},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "scraped_at", Type: field.TypeTime},
	}
	// MoviesTable holds the schema information for the "movies" table.
	MoviesTable = &schema.Table{
		Name:       "movies",
		Columns:    MoviesColumns,
		PrimaryKey: []*schema.Column{MoviesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "movie_user_id_url",
				Unique:  true,
				Columns: []*schema.Column{MoviesColumns[1], MoviesColumns[3]},
			},
		},
	}
	// NotesColumns holds the columns for the "notes" table.
	NotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "title", Type: field.TypeString},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "date", Type: field.TypeString, Nullable: true},
		{Name: "location", Type: field.TypeString, Nullable: true},
		{Name: "body", Type: field.TypeString, Nullable: true},
		{Name: "scraped_at", Type: field.TypeTime},
	}
	// NotesTable holds the schema information for the "notes" table.
	NotesTable = &schema.Table{
		Name:       "notes",
		Columns:    NotesColumns,
		PrimaryKey: []*schema.Column{NotesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "note_user_id_url",
				Unique:  true,
				Columns: []*schema.Column{NotesColumns[1], NotesColumns[3]},
			},
		},
	}
	// PlatformsColumns holds the columns for the "platforms" table.
	PlatformsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true, SchemaType: map[string]string{"postgres": "serial"}},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// PlatformsTable holds the schema information for the "platforms" table.
	PlatformsTable = &schema.Table{
		Name:       "platforms",
		Columns:    PlatformsColumns,
		PrimaryKey: []*schema.Column{PlatformsColumns[0]},
	}
	// ReviewsColumns holds the columns for the "reviews" table.
	ReviewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "subject_title", Type: field.TypeString},
		{Name: "subject_url", Type: field.TypeString, Nullable: true},
		{Name: "subject_img_url", Type: field.TypeString, Nullable: true},
		{Name: "review_title", Type: field.TypeString, Nullable: true},
		{Name: "review_url", Type: field.TypeString, Nullable: true},
		{Name: "date", Type: field.TypeString, Nullable: true},
		{Name: "scraped_at", Type: field.TypeTime},
	}
	// ReviewsTable holds the schema information for the "reviews" table.
	ReviewsTable = &schema.Table{
		Name:       "reviews",
		Columns:    ReviewsColumns,
		PrimaryKey: []*schema.Column{ReviewsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "review_user_id_review_url",
				Unique:  true,
				Columns: []*schema.Column{ReviewsColumns[1], ReviewsColumns[6]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "session_id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "title", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "bigserial"}},
		{Name: "user_id", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "bio", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "email_verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BooksTable,
		BookmarksTable,
		CommunityMetaTable,
		FlomoMemosTable,
		GamesTable,
		MessagesTable,
		MoviesTable,
		NotesTable,
		PlatformsTable,
		ReviewsTable,
		SessionsTable,
		UsersTable,
	}
)

func init() {
}
