// Code generated by ent, DO NOT EDIT.

package review

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lifeink-ai/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldUserID, v))
}

// SubjectTitle applies equality check predicate on the "subject_title" field. It's identical to SubjectTitleEQ.
func SubjectTitle(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldSubjectTitle, v))
}

// SubjectURL applies equality check predicate on the "subject_url" field. It's identical to SubjectURLEQ.
func SubjectURL(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldSubjectURL, v))
}

// SubjectImgURL applies equality check predicate on the "subject_img_url" field. It's identical to SubjectImgURLEQ.
func SubjectImgURL(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldSubjectImgURL, v))
}

// ReviewTitle applies equality check predicate on the "review_title" field. It's identical to ReviewTitleEQ.
func ReviewTitle(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldReviewTitle, v))
}

// ReviewURL applies equality check predicate on the "review_url" field. It's identical to ReviewURLEQ.
func ReviewURL(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldReviewURL, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldDate, v))
}

// ScrapedAt applies equality check predicate on the "scraped_at" field. It's identical to ScrapedAtEQ.
func ScrapedAt(v time.Time) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldScrapedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldUserID, v))
}

// SubjectTitleEQ applies the EQ predicate on the "subject_title" field.
func SubjectTitleEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldSubjectTitle, v))
}

// SubjectTitleNEQ applies the NEQ predicate on the "subject_title" field.
func SubjectTitleNEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldSubjectTitle, v))
}

// SubjectTitleIn applies the In predicate on the "subject_title" field.
func SubjectTitleIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldSubjectTitle, vs...))
}

// SubjectTitleNotIn applies the NotIn predicate on the "subject_title" field.
func SubjectTitleNotIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldSubjectTitle, vs...))
}

// SubjectTitleGT applies the GT predicate on the "subject_title" field.
func SubjectTitleGT(v string) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldSubjectTitle, v))
}

// SubjectTitleGTE applies the GTE predicate on the "subject_title" field.
func SubjectTitleGTE(v string) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldSubjectTitle, v))
}

// SubjectTitleLT applies the LT predicate on the "subject_title" field.
func SubjectTitleLT(v string) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldSubjectTitle, v))
}

// SubjectTitleLTE applies the LTE predicate on the "subject_title" field.
func SubjectTitleLTE(v string) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldSubjectTitle, v))
}

// SubjectTitleContains applies the Contains predicate on the "subject_title" field.
func SubjectTitleContains(v string) predicate.Review {
	return predicate.Review(sql.FieldContains(FieldSubjectTitle, v))
}

// SubjectTitleHasPrefix applies the HasPrefix predicate on the "subject_title" field.
func SubjectTitleHasPrefix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasPrefix(FieldSubjectTitle, v))
}

// SubjectTitleHasSuffix applies the HasSuffix predicate on the "subject_title" field.
func SubjectTitleHasSuffix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasSuffix(FieldSubjectTitle, v))
}

// SubjectTitleEqualFold applies the EqualFold predicate on the "subject_title" field.
func SubjectTitleEqualFold(v string) predicate.Review {
	return predicate.Review(sql.FieldEqualFold(FieldSubjectTitle, v))
}

// SubjectTitleContainsFold applies the ContainsFold predicate on the "subject_title" field.
func SubjectTitleContainsFold(v string) predicate.Review {
	return predicate.Review(sql.FieldContainsFold(FieldSubjectTitle, v))
}

// SubjectURLEQ applies the EQ predicate on the "subject_url" field.
func SubjectURLEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldSubjectURL, v))
}

// SubjectURLNEQ applies the NEQ predicate on the "subject_url" field.
func SubjectURLNEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldSubjectURL, v))
}

// SubjectURLIn applies the In predicate on the "subject_url" field.
func SubjectURLIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldSubjectURL, vs...))
}

// SubjectURLNotIn applies the NotIn predicate on the "subject_url" field.
func SubjectURLNotIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldSubjectURL, vs...))
}

// SubjectURLGT applies the GT predicate on the "subject_url" field.
func SubjectURLGT(v string) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldSubjectURL, v))
}

// SubjectURLGTE applies the GTE predicate on the "subject_url" field.
func SubjectURLGTE(v string) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldSubjectURL, v))
}

// SubjectURLLT applies the LT predicate on the "subject_url" field.
func SubjectURLLT(v string) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldSubjectURL, v))
}

// SubjectURLLTE applies the LTE predicate on the "subject_url" field.
func SubjectURLLTE(v string) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldSubjectURL, v))
}

// SubjectURLContains applies the Contains predicate on the "subject_url" field.
func SubjectURLContains(v string) predicate.Review {
	return predicate.Review(sql.FieldContains(FieldSubjectURL, v))
}

// SubjectURLHasPrefix applies the HasPrefix predicate on the "subject_url" field.
func SubjectURLHasPrefix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasPrefix(FieldSubjectURL, v))
}

// SubjectURLHasSuffix applies the HasSuffix predicate on the "subject_url" field.
func SubjectURLHasSuffix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasSuffix(FieldSubjectURL, v))
}

// SubjectURLIsNil applies the IsNil predicate on the "subject_url" field.
func SubjectURLIsNil() predicate.Review {
	return predicate.Review(sql.FieldIsNull(FieldSubjectURL))
}

// SubjectURLNotNil applies the NotNil predicate on the "subject_url" field.
func SubjectURLNotNil() predicate.Review {
	return predicate.Review(sql.FieldNotNull(FieldSubjectURL))
}

// SubjectURLEqualFold applies the EqualFold predicate on the "subject_url" field.
func SubjectURLEqualFold(v string) predicate.Review {
	return predicate.Review(sql.FieldEqualFold(FieldSubjectURL, v))
}

// SubjectURLContainsFold applies the ContainsFold predicate on the "subject_url" field.
func SubjectURLContainsFold(v string) predicate.Review {
	return predicate.Review(sql.FieldContainsFold(FieldSubjectURL, v))
}

// SubjectImgURLEQ applies the EQ predicate on the "subject_img_url" field.
func SubjectImgURLEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldSubjectImgURL, v))
}

// SubjectImgURLNEQ applies the NEQ predicate on the "subject_img_url" field.
func SubjectImgURLNEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldSubjectImgURL, v))
}

// SubjectImgURLIn applies the In predicate on the "subject_img_url" field.
func SubjectImgURLIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldSubjectImgURL, vs...))
}

// SubjectImgURLNotIn applies the NotIn predicate on the "subject_img_url" field.
func SubjectImgURLNotIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldSubjectImgURL, vs...))
}

// SubjectImgURLGT applies the GT predicate on the "subject_img_url" field.
func SubjectImgURLGT(v string) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldSubjectImgURL, v))
}

// SubjectImgURLGTE applies the GTE predicate on the "subject_img_url" field.
func SubjectImgURLGTE(v string) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldSubjectImgURL, v))
}

// SubjectImgURLLT applies the LT predicate on the "subject_img_url" field.
func SubjectImgURLLT(v string) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldSubjectImgURL, v))
}

// SubjectImgURLLTE applies the LTE predicate on the "subject_img_url" field.
func SubjectImgURLLTE(v string) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldSubjectImgURL, v))
}

// SubjectImgURLContains applies the Contains predicate on the "subject_img_url" field.
func SubjectImgURLContains(v string) predicate.Review {
	return predicate.Review(sql.FieldContains(FieldSubjectImgURL, v))
}

// SubjectImgURLHasPrefix applies the HasPrefix predicate on the "subject_img_url" field.
func SubjectImgURLHasPrefix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasPrefix(FieldSubjectImgURL, v))
}

// SubjectImgURLHasSuffix applies the HasSuffix predicate on the "subject_img_url" field.
func SubjectImgURLHasSuffix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasSuffix(FieldSubjectImgURL, v))
}

// SubjectImgURLIsNil applies the IsNil predicate on the "subject_img_url" field.
func SubjectImgURLIsNil() predicate.Review {
	return predicate.Review(sql.FieldIsNull(FieldSubjectImgURL))
}

// SubjectImgURLNotNil applies the NotNil predicate on the "subject_img_url" field.
func SubjectImgURLNotNil() predicate.Review {
	return predicate.Review(sql.FieldNotNull(FieldSubjectImgURL))
}

// SubjectImgURLEqualFold applies the EqualFold predicate on the "subject_img_url" field.
func SubjectImgURLEqualFold(v string) predicate.Review {
	return predicate.Review(sql.FieldEqualFold(FieldSubjectImgURL, v))
}

// SubjectImgURLContainsFold applies the ContainsFold predicate on the "subject_img_url" field.
func SubjectImgURLContainsFold(v string) predicate.Review {
	return predicate.Review(sql.FieldContainsFold(FieldSubjectImgURL, v))
}

// ReviewTitleEQ applies the EQ predicate on the "review_title" field.
func ReviewTitleEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldReviewTitle, v))
}

// ReviewTitleNEQ applies the NEQ predicate on the "review_title" field.
func ReviewTitleNEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldReviewTitle, v))
}

// ReviewTitleIn applies the In predicate on the "review_title" field.
func ReviewTitleIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldReviewTitle, vs...))
}

// ReviewTitleNotIn applies the NotIn predicate on the "review_title" field.
func ReviewTitleNotIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldReviewTitle, vs...))
}

// ReviewTitleGT applies the GT predicate on the "review_title" field.
func ReviewTitleGT(v string) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldReviewTitle, v))
}

// ReviewTitleGTE applies the GTE predicate on the "review_title" field.
func ReviewTitleGTE(v string) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldReviewTitle, v))
}

// ReviewTitleLT applies the LT predicate on the "review_title" field.
func ReviewTitleLT(v string) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldReviewTitle, v))
}

// ReviewTitleLTE applies the LTE predicate on the "review_title" field.
func ReviewTitleLTE(v string) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldReviewTitle, v))
}

// ReviewTitleContains applies the Contains predicate on the "review_title" field.
func ReviewTitleContains(v string) predicate.Review {
	return predicate.Review(sql.FieldContains(FieldReviewTitle, v))
}

// ReviewTitleHasPrefix applies the HasPrefix predicate on the "review_title" field.
func ReviewTitleHasPrefix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasPrefix(FieldReviewTitle, v))
}

// ReviewTitleHasSuffix applies the HasSuffix predicate on the "review_title" field.
func ReviewTitleHasSuffix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasSuffix(FieldReviewTitle, v))
}

// ReviewTitleIsNil applies the IsNil predicate on the "review_title" field.
func ReviewTitleIsNil() predicate.Review {
	return predicate.Review(sql.FieldIsNull(FieldReviewTitle))
}

// ReviewTitleNotNil applies the NotNil predicate on the "review_title" field.
func ReviewTitleNotNil() predicate.Review {
	return predicate.Review(sql.FieldNotNull(FieldReviewTitle))
}

// ReviewTitleEqualFold applies the EqualFold predicate on the "review_title" field.
func ReviewTitleEqualFold(v string) predicate.Review {
	return predicate.Review(sql.FieldEqualFold(FieldReviewTitle, v))
}

// ReviewTitleContainsFold applies the ContainsFold predicate on the "review_title" field.
func ReviewTitleContainsFold(v string) predicate.Review {
	return predicate.Review(sql.FieldContainsFold(FieldReviewTitle, v))
}

// ReviewURLEQ applies the EQ predicate on the "review_url" field.
func ReviewURLEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldReviewURL, v))
}

// ReviewURLNEQ applies the NEQ predicate on the "review_url" field.
func ReviewURLNEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldReviewURL, v))
}

// ReviewURLIn applies the In predicate on the "review_url" field.
func ReviewURLIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldReviewURL, vs...))
}

// ReviewURLNotIn applies the NotIn predicate on the "review_url" field.
func ReviewURLNotIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldReviewURL, vs...))
}

// ReviewURLGT applies the GT predicate on the "review_url" field.
func ReviewURLGT(v string) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldReviewURL, v))
}

// ReviewURLGTE applies the GTE predicate on the "review_url" field.
func ReviewURLGTE(v string) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldReviewURL, v))
}

// ReviewURLLT applies the LT predicate on the "review_url" field.
func ReviewURLLT(v string) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldReviewURL, v))
}

// ReviewURLLTE applies the LTE predicate on the "review_url" field.
func ReviewURLLTE(v string) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldReviewURL, v))
}

// ReviewURLContains applies the Contains predicate on the "review_url" field.
func ReviewURLContains(v string) predicate.Review {
	return predicate.Review(sql.FieldContains(FieldReviewURL, v))
}

// ReviewURLHasPrefix applies the HasPrefix predicate on the "review_url" field.
func ReviewURLHasPrefix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasPrefix(FieldReviewURL, v))
}

// ReviewURLHasSuffix applies the HasSuffix predicate on the "review_url" field.
func ReviewURLHasSuffix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasSuffix(FieldReviewURL, v))
}

// ReviewURLIsNil applies the IsNil predicate on the "review_url" field.
func ReviewURLIsNil() predicate.Review {
	return predicate.Review(sql.FieldIsNull(FieldReviewURL))
}

// ReviewURLNotNil applies the NotNil predicate on the "review_url" field.
func ReviewURLNotNil() predicate.Review {
	return predicate.Review(sql.FieldNotNull(FieldReviewURL))
}

// ReviewURLEqualFold applies the EqualFold predicate on the "review_url" field.
func ReviewURLEqualFold(v string) predicate.Review {
	return predicate.Review(sql.FieldEqualFold(FieldReviewURL, v))
}

// ReviewURLContainsFold applies the ContainsFold predicate on the "review_url" field.
func ReviewURLContainsFold(v string) predicate.Review {
	return predicate.Review(sql.FieldContainsFold(FieldReviewURL, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v string) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...string) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v string) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v string) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v string) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v string) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldDate, v))
}

// DateContains applies the Contains predicate on the "date" field.
func DateContains(v string) predicate.Review {
	return predicate.Review(sql.FieldContains(FieldDate, v))
}

// DateHasPrefix applies the HasPrefix predicate on the "date" field.
func DateHasPrefix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasPrefix(FieldDate, v))
}

// DateHasSuffix applies the HasSuffix predicate on the "date" field.
func DateHasSuffix(v string) predicate.Review {
	return predicate.Review(sql.FieldHasSuffix(FieldDate, v))
}

// DateIsNil applies the IsNil predicate on the "date" field.
func DateIsNil() predicate.Review {
	return predicate.Review(sql.FieldIsNull(FieldDate))
}

// DateNotNil applies the NotNil predicate on the "date" field.
func DateNotNil() predicate.Review {
	return predicate.Review(sql.FieldNotNull(FieldDate))
}

// DateEqualFold applies the EqualFold predicate on the "date" field.
func DateEqualFold(v string) predicate.Review {
	return predicate.Review(sql.FieldEqualFold(FieldDate, v))
}

// DateContainsFold applies the ContainsFold predicate on the "date" field.
func DateContainsFold(v string) predicate.Review {
	return predicate.Review(sql.FieldContainsFold(FieldDate, v))
}

// ScrapedAtEQ applies the EQ predicate on the "scraped_at" field.
func ScrapedAtEQ(v time.Time) predicate.Review {
	return predicate.Review(sql.FieldEQ(FieldScrapedAt, v))
}

// ScrapedAtNEQ applies the NEQ predicate on the "scraped_at" field.
func ScrapedAtNEQ(v time.Time) predicate.Review {
	return predicate.Review(sql.FieldNEQ(FieldScrapedAt, v))
}

// ScrapedAtIn applies the In predicate on the "scraped_at" field.
func ScrapedAtIn(vs ...time.Time) predicate.Review {
	return predicate.Review(sql.FieldIn(FieldScrapedAt, vs...))
}

// ScrapedAtNotIn applies the NotIn predicate on the "scraped_at" field.
func ScrapedAtNotIn(vs ...time.Time) predicate.Review {
	return predicate.Review(sql.FieldNotIn(FieldScrapedAt, vs...))
}

// ScrapedAtGT applies the GT predicate on the "scraped_at" field.
func ScrapedAtGT(v time.Time) predicate.Review {
	return predicate.Review(sql.FieldGT(FieldScrapedAt, v))
}

// ScrapedAtGTE applies the GTE predicate on the "scraped_at" field.
func ScrapedAtGTE(v time.Time) predicate.Review {
	return predicate.Review(sql.FieldGTE(FieldScrapedAt, v))
}

// ScrapedAtLT applies the LT predicate on the "scraped_at" field.
func ScrapedAtLT(v time.Time) predicate.Review {
	return predicate.Review(sql.FieldLT(FieldScrapedAt, v))
}

// ScrapedAtLTE applies the LTE predicate on the "scraped_at" field.
func ScrapedAtLTE(v time.Time) predicate.Review {
	return predicate.Review(sql.FieldLTE(FieldScrapedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Review) predicate.Review {
	return predicate.Review(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Review) predicate.Review {
	return predicate.Review(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Review) predicate.Review {
	return predicate.Review(sql.NotPredicates(p))
}
